extends RefCounted
const TestSupport=preload("res://tests/test_support.gd")

static func configure(main:Node,hero:Dictionary,build_index:int)->void:main.load_vitalist_test_build(hero,build_index)

static func run(main:Node)->Array:
	var errors:Array=[];var vitalist_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Vitalist")
	if vitalist_index<0:TestSupport.check(errors,false,"The testing save should include a Vitalist fixture.");return errors
	var cleric_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Cleric");var guardian_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Guardian");var vanguard_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Vanguard")
	main.state.selected_team=[vitalist_index,cleric_index,guardian_index,vanguard_index];main.state.active_team=main.state.selected_team.duplicate();main.start_vitalist_testing_zone()
	var hero:Dictionary=main.heroes.filter(func(member):return str(member.get("class",""))=="Vitalist")[0];main.selected=main.heroes.find(hero);var ally:Dictionary=main.heroes.filter(func(member):return str(member.get("class",""))=="Cleric")[0];var foe:Dictionary=main.enemies[0];hero.pos=Vector2(325,420);ally.pos=hero.pos+Vector2(45,0);ally.hp=ally.max_hp*.25;foe.pos=hero.pos+Vector2(120,0);foe.hp=15000.0;foe.max_hp=15000.0;foe.armor=0.0
	configure(main,hero,0);hero.pos=Vector2(325,420);ally.pos=hero.pos+Vector2(45,0);ally.hp=ally.max_hp*.25;TestSupport.check(errors,main.cast_vitalist_ability(0,ally.pos) and hero.vitalist_runtime.q_infections.size()==1,"Live Q should create a source-owned Pathogen on the selected nearby ally.");var ally_before:=float(ally.hp);main.update_vitalist_runtime(.5);TestSupport.check(errors,float(ally.hp)>ally_before,"Live Pathogen should perform periodic healing.")
	configure(main,hero,0);hero.pos=Vector2(325,420);foe.pos=hero.pos+Vector2(120,0);var foe_before:=float(foe.hp);TestSupport.check(errors,main.cast_vitalist_ability(1,foe.pos) and hero.vitalist_runtime.w_infections.has(str(foe.combat_id)) and float(foe.hp)<foe_before,"Live W should damage and create an owned hostile infection.");main.update_vitalist_runtime(1.0);TestSupport.check(errors,main.StatusEffectSystem.has_control(foe,"slow"),"Live W should maintain its source-aware ramping Slow.")
	var d_before:=float(foe.hp);TestSupport.check(errors,main.cast_vitalist_ability(4,hero.pos) and float(foe.hp)<d_before and hero.vitalist_runtime.w_infections.is_empty(),"Live D should snapshot, damage, Slow, and remove W.")
	configure(main,hero,3);hero.pos=Vector2(325,420);foe.pos=Vector2(560,300);TestSupport.check(errors,main.cast_vitalist_ability(2,foe.pos) and not hero.vitalist_runtime.arm.is_empty(),"Live E should begin its placed channel.");foe.pos=hero.vitalist_runtime.arm.position;foe_before=float(foe.hp);main.update_vitalist_runtime(.5);TestSupport.check(errors,float(foe.hp)<foe_before and main.StatusEffectSystem.has_control(foe,"silence"),"Live E should deal full PvE damage and apply profile-aware Silence.");TestSupport.check(errors,main.cast_vitalist_ability(4,hero.pos),"D should remain usable during E.");TestSupport.check(errors,not main.cast_vitalist_ability(0,ally.pos) and not main.cast_vitalist_ability(1,foe.pos),"Q and W should remain locked during E.")
	configure(main,hero,3);hero.pos=Vector2(325,420);foe.pos=Vector2(560,300);main.cast_vitalist_ability(2,foe.pos);foe.pos=hero.pos+Vector2(120,0);TestSupport.check(errors,main.cast_vitalist_ability(3,foe.pos) and not hero.vitalist_runtime.arm.is_empty(),"Bio-Explosion Switch should allow selected Massive Shove during E without cancelling E.")
	configure(main,hero,2);hero.hp=hero.max_hp*.49;for enemy in main.enemies.slice(0,3):enemy.pos=hero.pos+Vector2(70+main.enemies.find(enemy)*25,0)
	TestSupport.check(errors,main.cast_vitalist_ability(4,hero.pos) and hero.vitalist_runtime.w_infections.size()>0,"Reactive Ballistospores plus Poppin' Pustules should detonate pre-snapshot W and leave post-resolution replacement W infections.")
	configure(main,hero,2);hero.pos=Vector2(800,240);foe.pos=Vector2(900,240);for other in main.enemies:if other!=foe:other.pos=Vector2(250,100+main.enemies.find(other)*20)
	var shove_start:=Vector2(foe.pos);TestSupport.check(errors,main.cast_vitalist_ability(3,Vector2(1225,240)) and not hero.vitalist_runtime.shove.is_empty() and not main.cast_vitalist_ability(0,ally.pos),"Massive Shove should enter an action-locking explicit channel state.");main.update_vitalist_runtime(.25);TestSupport.check(errors,Vector2(foe.pos).x>shove_start.x and not hero.vitalist_runtime.shove.is_empty(),"Massive Shove should advance its captured target frame-by-frame at audited velocity.");main.update_vitalist_runtime(2.0);TestSupport.check(errors,hero.vitalist_runtime.shove.is_empty() and Vector2(foe.pos).x<=float(main.CombatGeometry.BATTLE_BOUNDS.end.x)-float(foe.get("combat_radius",24.0))+.01 and main.StatusEffectSystem.has_control(foe,"slow"),"Massive Shove should stop at a radius-safe authored boundary and apply Push Comes to Shove on collision.")
	configure(main,hero,1);hero.pos=Vector2(325,420);foe.pos=hero.pos+Vector2(100,0);TestSupport.check(errors,main.cast_vitalist_ability(3,foe.pos),"Controlled Chaos should cast from the live action bar.");main.update_vitalist_runtime(0.01);TestSupport.check(errors,int(main.VitalistSystem.r_ui(hero).charges)==2,"Controlled Chaos should visibly consume one of three R charges.")
	TestSupport.check(errors,main.combat_blockers.size()>=2 and main.enemies.size()>=8 and main.heroes.size()==4,"Vitalist Testing Range should include party, control-profile, group, terrain, and boundary fixtures.")
	return errors
