extends RefCounted
const TestSupport=preload("res://tests/test_support.gd")

static func configure(main:Node,hero:Dictionary,build_index:int)->void:
	var build:Dictionary=main.VanguardData.TEST_BUILDS[build_index];var level:=int(build.level);hero.level=level;hero.base_power=main.VanguardData.scaled(float(main.VanguardData.VALUES.basic_attack_damage),level);hero.power=hero.base_power;hero.damage=hero.base_power;hero.max_hp=main.VanguardData.scaled(float(main.VanguardData.VALUES.health),level);hero.hp=hero.max_hp;hero.selected_heroic_id=str(build.heroic);hero.selected_talents=build.talents.duplicate(true);hero.ability_cds=[0.0,0.0,0.0,0.0,0.0];hero.active_effects=[];hero.temporary_armor_sources=[];hero.block_state={};main.VanguardSystem.initialize_runtime(hero,true,"testing:vanguard")

static func run(main:Node)->Array:
	var errors:Array=[];var vanguard_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Vanguard")
	if vanguard_index<0:TestSupport.check(errors,false,"The testing save should include a Vanguard fixture.");return errors
	var cleric_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Cleric");var guardian_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Guardian");var crusader_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Crusader")
	main.state.selected_team=[vanguard_index,cleric_index,guardian_index,crusader_index];main.state.active_team=main.state.selected_team.duplicate();main.start_vanguard_testing_zone()
	var hero:Dictionary=main.heroes.filter(func(member):return str(member.get("class",""))=="Vanguard")[0];main.selected=main.heroes.find(hero);var ally:Dictionary=main.heroes.filter(func(member):return str(member.get("class",""))=="Cleric")[0];var foe:Dictionary=main.enemies[0];hero.pos=Vector2(330,390);hero.facing_direction=Vector2.RIGHT;ally.pos=hero.pos+Vector2(40,0);foe.pos=hero.pos+Vector2(100,0);foe.hp=15000.0;foe.max_hp=15000.0;foe.armor=0.0
	main.load_vanguard_test_build(hero,1);TestSupport.check(errors,str(hero.selected_heroic_id)=="vanguard_l15_r1" and main.VanguardSystem.has_talent(hero,"vanguard_l27_r1") and is_equal_approx(float(hero.hp),float(hero.max_hp)),"The Vanguard range loader should equip and fully initialize an approved build.")
	configure(main,hero,0);hero.pos=Vector2(330,390);foe.pos=hero.pos+Vector2(100,0);var before:=float(foe.hp);TestSupport.check(errors,main.cast_vanguard_ability(0,hero.pos+Vector2(240,0)) and float(foe.hp)<before and main.StatusEffectSystem.has_control(foe,"stun") and float(hero.temporary_armor_sources[0].armor)>0.0,"Live Powerslide should move, damage, Stun, and trigger Rockstar once.")
	configure(main,hero,0);hero.pos=Vector2(330,390);foe.pos=hero.pos+Vector2(65,0);var old_pos:=Vector2(foe.pos);TestSupport.check(errors,main.cast_vanguard_ability(1,hero.pos) and Vector2(foe.pos).distance_to(hero.pos)>old_pos.distance_to(hero.pos),"Live Face Melt should safely knock a susceptible nearby target away.")
	configure(main,hero,0);hero.pos=Vector2(330,390);foe.pos=hero.pos+Vector2(50,0);var hero_facing:=Vector2.RIGHT;hero.facing_direction=hero_facing;TestSupport.check(errors,main.cast_vanguard_ability(2,foe.pos) and Vector2(foe.pos).x<float(hero.pos.x) and main.StatusEffectSystem.has_control(foe,"stun"),"Live Overpower should safely flip a susceptible target behind Vanguard, damage, and Stun.")
	configure(main,hero,1);hero.pos=Vector2(330,390);foe.pos=hero.pos+Vector2(80,0);TestSupport.check(errors,main.cast_vanguard_ability(3,hero.pos) and is_equal_approx(float(hero.ability_cds[0]),0.0),"Tour Bus Mosh should refresh Q on cast.");main.update_vanguard_runtime(.75);TestSupport.check(errors,not hero.vanguard_runtime.mosh.is_empty(),"Mosh Pit should begin after its 0.75-second windup.");main.update_vanguard_runtime(.05);TestSupport.check(errors,main.StatusEffectSystem.has_control(foe,"stun"),"Active Mosh should continuously maintain its source-owned Stun aura.");hero.ability_cds[0]=0.0;var previous_remaining:=float(hero.vanguard_runtime.mosh.remaining);main.cast_vanguard_ability(0,hero.pos+Vector2(120,0));TestSupport.check(errors,float(hero.vanguard_runtime.mosh.remaining)>previous_remaining and float(hero.vanguard_runtime.telemetry.tour_slides)>=1.0,"Tour Bus should allow Q during Mosh and extend the moving aura by two seconds.")
	configure(main,hero,2);hero.pos=Vector2(330,390);hero.facing_direction=Vector2.RIGHT;foe.pos=hero.pos+Vector2(100,0);before=float(foe.hp);TestSupport.check(errors,main.cast_vanguard_ability(3,hero.pos),"Lightning Breath should commit from the live action bar.");main.update_vanguard_runtime(.5);main.update_vanguard_runtime(.25);TestSupport.check(errors,float(foe.hp)<before and main.StatusEffectSystem.has_control(foe,"slow") and main.StatusEffectSystem.is_unstoppable(hero),"Lightning Breath should tick frontal damage, source-owned Slow, and Unstoppable after its windup.");var fixed_pos:=Vector2(hero.pos);main.issue_hero_move(hero,hero.pos+Vector2.UP*100.0);TestSupport.check(errors,Vector2(hero.pos)==fixed_pos and Vector2(hero.facing_direction).dot(Vector2.UP)>.99,"A Vanguard-specific movement command should rotate Lightning Breath without moving or cancelling it.")
	configure(main,hero,2);ally.pos=hero.pos+Vector2(40,0);ally.block_state={};main.cast_vanguard_ability(3,hero.pos);TestSupport.check(errors,ally.get("temporary_armor_sources",[]).any(func(source):return str(source.get("id","")).begins_with("vanguard_rockstar") and float(source.armor)>0.0) and main.BlockChargeSystem.charges(ally)==1,"Power of the Horde and Block Party should use the shared nearby-recipient support radius on one committed Heroic.")
	configure(main,hero,3);hero.hp=hero.max_hp;main.deal_damage(foe,hero,float(hero.max_hp)+100.0,"basic_attack","physical","Lethal",false,"",[],false);TestSupport.check(errors,is_equal_approx(float(hero.hp),1.0) and not hero.vanguard_runtime.mosh.is_empty() and is_equal_approx(float(hero.vanguard_runtime.death_metal_icd),120.0),"Selected Lightning Breath should intercept fatal damage at one Health and immediately start baseline emergency Mosh with its independent 120-second ICD.");main.deal_healing(ally,hero,float(hero.max_hp)*.40,"basic_ability","Save");main.update_vanguard_runtime(4.0);TestSupport.check(errors,float(hero.hp)>0.0 and hero.vanguard_runtime.death_metal.is_empty(),"Death Metal should allow ordinary healing and survive the end check at 35% or more current Health.")
	TestSupport.check(errors,main.combat_blockers.size()>0 and main.enemies.size()>=6,"Vanguard Testing Range should include blockers and multi-target fixtures.")
	return errors
