extends RefCounted

const TestSupport=preload("res://tests/test_support.gd")

static func run(main:Node)->Array:
	var errors:Array=[];var save_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Warrior")
	if save_index<0:TestSupport.check(errors,false,"The testing save should include a Warrior runtime fixture.");return errors
	main.state.selected_team=[save_index];main.state.active_team=[save_index];main.start_warrior_testing_zone();var warrior:Dictionary=main.heroes[0];main.selected=0
	TestSupport.check(errors,main.testing_zone_mode=="warrior_range" and main.enemies.any(func(enemy):return str(enemy.get("target_category",""))=="summon") and main.enemies.any(func(enemy):return str(enemy.get("target_category",""))=="boss") and main.combat_blockers.any(func(blocker):return str(blocker.get("combat_id",""))=="blocker:warrior_landing"),"Warrior Range should launch with summon, Boss, shield, and safe-landing fixtures.")

	main.load_warrior_test_build(warrior,0);warrior.critical_chance=0.0;var target:Dictionary=main.enemies[0];target.armor=0.0;target.shield=0.0;target.hp=1000.0;target.max_hp=1000.0;warrior.warrior_runtime.heroic_strike_cooldown=0.0;var hp_before:=float(target.hp)
	main.deal_damage(warrior,target,float(warrior.damage),"basic_attack","physical","Warrior Basic Attack")
	TestSupport.check(errors,is_equal_approx(hp_before-float(target.hp),199.0) and is_equal_approx(float(warrior.warrior_runtime.heroic_strike_cooldown),15.0),"A live empowered Basic Attack should resolve 74 primary plus a separate 125 Heroic Strike packet, then apply three-second CDR.")
	main.EvasionSystem.activate(target,1.0,"warrior_test");warrior.warrior_runtime.heroic_strike_cooldown=0.0;main.deal_damage(warrior,target,float(warrior.damage),"basic_attack","physical","Warrior Basic Attack")
	TestSupport.check(errors,is_equal_approx(float(warrior.warrior_runtime.heroic_strike_cooldown),18.0),"A live evaded empowered attack should consume the proc and reset Heroic Strike to 18 seconds without success CDR.")

	main.load_warrior_test_build(warrior,4);var summon:Dictionary=main.enemies.filter(func(enemy):return str(enemy.get("target_category",""))=="summon")[0];summon.pos=warrior.pos+Vector2(100,0);summon.remaining_lifetime=25.0;summon.original_lifetime=25.0;summon.hp=10000.0;summon.max_hp=10000.0;var summon_before:=float(summon.hp);main.cast_warrior_lions_fang(warrior,summon.pos)
	TestSupport.check(errors,is_equal_approx(float(summon.remaining_lifetime),24.0) and summon_before-float(summon.hp)>=400.0,"Live Lion's Fang should apply Juggernaut's 4% maximum-Health packet and remove 4% original summon lifetime.")

	main.load_warrior_test_build(warrior,1);var boss:Dictionary=main.enemies.filter(func(enemy):return str(enemy.get("target_category",""))=="boss")[0];boss.pos=warrior.pos+Vector2(40,0);main.focused_enemy_index=main.enemies.find(boss);TestSupport.check(errors,main.cast_warrior_heroic(warrior) and main.ForcedTargetSystem.preferred(boss)==0 and main.CombatSystem.is_silenced(boss),"Taunt should force even a Boss to target the Warrior and apply the Silence control profile.")
	warrior.warrior_runtime.heroic_strike_cooldown=0.0;boss.hp=boss.max_hp;main.deal_damage(warrior,boss,float(warrior.damage),"basic_attack","physical","Warrior Basic Attack");TestSupport.check(errors,is_equal_approx(main.HealingReceivedModifierSystem.multiplier(boss),.6),"A successful live Heroic Strike with Mortal Strike should reduce healing received by 40%.")
	main.WarriorSystem.cast_parry(warrior);var protected_result:Dictionary=main.deal_damage(boss,warrior,100.0,"basic_attack","physical","Boss Basic Attack");TestSupport.check(errors,bool(protected_result.immune) and is_equal_approx(float(protected_result.resolved_damage),0.0),"Shield Wall should resolve hostile Basic Attack contact triggers while Protected prevents the damage.")

	main.load_warrior_test_build(warrior,3);warrior.warrior_runtime.twin_move_remaining=2.0;TestSupport.check(errors,is_equal_approx(main.active_movement_multiplier(warrior),1.4),"Frenzy should raise Twin Blades' successful-attack movement bonus to 40%.");var shielded:Dictionary=main.enemies[-1];shielded.pos=warrior.pos+Vector2(100,0);shielded.hp=5000.0;shielded.max_hp=5000.0;shielded.shield=1800.0;shielded.shield_sources=[{"source_id":"test","amount":1800.0}];main.focused_enemy_index=main.enemies.find(shielded);var health_before:=float(shielded.hp);TestSupport.check(errors,main.cast_warrior_trait(warrior) and shielded.shield<400.0 and is_equal_approx(float(shielded.hp),health_before),"Shattering Throw should deal its normal packet into the shield plus 1400 shield-only damage without spillover.")
	warrior.warrior_runtime.heroic_strike_cooldown=18.0;shielded.hp=5000.0;shielded.shield=float(warrior.damage)+20.0;shielded.shield_sources=[{"source_id":"basic_passive","amount":shielded.shield}];health_before=float(shielded.hp);main.deal_damage(warrior,shielded,float(warrior.damage),"basic_attack","physical","Warrior Basic Attack");TestSupport.check(errors,is_equal_approx(float(shielded.shield),0.0) and is_equal_approx(float(shielded.hp),health_before),"Shattering Throw's Basic Attack passive should finish a shield with up to 200% bonus even when the primary packet would otherwise break it, without bonus spillover.")

	main.load_warrior_test_build(warrior,0);warrior.pos=Vector2(200,400);warrior.dest=warrior.pos;warrior.hp=warrior.max_hp-500.0;for foe in main.enemies:foe.pos=Vector2(1100,650);foe.hp=5000.0;foe.max_hp=5000.0;foe.armor=0.0;foe.active_effects=[]
	var normal:Dictionary=main.enemies[0];normal.pos=warrior.pos+Vector2(100,0);boss.pos=warrior.pos+Vector2(200,0);var q_hp_before:=float(warrior.hp);var normal_before:=float(normal.hp);TestSupport.check(errors,main.cast_warrior_lions_fang(warrior,warrior.pos+Vector2.RIGHT*300.0) and is_equal_approx(normal_before-float(normal.hp),150.0) and is_equal_approx(float(warrior.hp)-q_hp_before,175.0) and main.CombatSystem.control_amount(normal,"slow")>=.35,"Live Lion's Fang should deal 150, Slow, and independently heal 35 plus 140 from normal and Boss contacts.")
	warrior.ability_cds[1]=0.0;warrior.hp=warrior.max_hp;TestSupport.check(errors,main.cast_warrior_parry(warrior),"Live baseline Parry should activate.");var ability_result:Dictionary=main.deal_damage(boss,warrior,100.0,"basic_ability","physical","Boss Ability");var basic_result:Dictionary=main.deal_damage(boss,warrior,100.0,"basic_attack","physical","Boss Basic Attack");TestSupport.check(errors,float(ability_result.resolved_damage)>0.0 and bool(basic_result.immune),"Baseline Parry should prevent hostile Basic Attacks while leaving Ability damage unaffected.")
	warrior.ability_cds[2]=0.0;normal.pos=warrior.pos+Vector2(80,0);main.focused_enemy_index=main.enemies.find(normal);normal_before=float(normal.hp);TestSupport.check(errors,main.cast_warrior_charge(warrior) and is_equal_approx(float(warrior.ability_cds[2]),12.0) and normal_before-float(normal.hp)>=50.0 and main.CombatSystem.control_amount(normal,"slow")>=.75,"Live enemy Charge should safely land, deal scaled baseline damage, Slow 75% for one second, and start 12 seconds.")

	var ally:={"class":"Cleric","combat_id":"hero:warrior_ally","combat_affiliation":"player","battle_index":1,"level":30,"hp":3000.0,"max_hp":3000.0,"health_regeneration":10.0,"pos":warrior.pos+Vector2(90,0),"dest":warrior.pos+Vector2(90,0),"combat_radius":42.0,"active_effects":[],"temporary_armor_sources":[],"healing_received_sources":[],"combat_quest_progress_sources":[],"movement_speed":150.0};main.heroes.append(ally)
	main.load_warrior_test_build(warrior,2);warrior.pos=Vector2(200,400);ally.pos=warrior.pos+Vector2(90,0);warrior.heal_target=main.heroes.find(ally);warrior.ability_cds[2]=0.0;var ally_hp_before:=float(ally.hp);TestSupport.check(errors,main.cast_warrior_charge(warrior) and is_equal_approx(float(warrior.ability_cds[2]),4.0) and is_equal_approx(float(ally.hp),ally_hp_before) and main.CombatSystem.control_amount(ally,"slow")<=0.0,"Warbringer should use the existing E slot to safely Charge an allied Hero on four seconds without ally damage or Slow.")

	warrior.pos=Vector2(200,400);warrior.dest=warrior.pos;for foe in main.enemies:foe.pos=Vector2(1100,650);foe.hp=5000.0;foe.max_hp=5000.0;foe.armor=100.0;foe.armor_reduction_sources=[];foe.active_effects=[]
	boss.pos=warrior.pos+Vector2(50,0);normal.pos=boss.pos+Vector2(30,0);var far_enemy:Dictionary=main.enemies[1] if main.enemies[1]!=boss and main.enemies[1]!=normal else main.enemies[2];far_enemy.pos=boss.pos+Vector2(200,0);main.focused_enemy_index=main.enemies.find(boss);var boss_before:=float(boss.hp);normal_before=float(normal.hp);var far_before:=float(far_enemy.hp);TestSupport.check(errors,main.cast_warrior_heroic(warrior) and float(boss.hp)<boss_before and float(normal.hp)<normal_before and is_equal_approx(float(far_enemy.hp),far_before) and is_equal_approx(float(warrior.warrior_runtime.taunt_cooldown),10.0) and main.ArmorReductionSystem.effective(boss)>25.0 and main.ArmorReductionSystem.effective(normal)>25.0,"Master at Arms should make Colossus a 10-second area hit with scaled source-aware Armor reduction and no distant contact.")
	main.load_warrior_test_build(warrior,3);TestSupport.check(errors,not main.cast_warrior_heroic(warrior),"Twin Blades R should remain passive and never cast an active Heroic.")

	warrior.pos=Vector2(300,400);ally.pos=warrior.pos;ally.active_effects=[];ally.temporary_armor_sources=[];ally.combat_quest_progress_sources=[];main.load_warrior_test_build(warrior,3);main.update_warrior_runtime(.1);TestSupport.check(errors,is_equal_approx(main.active_movement_multiplier(ally),1.25) and main.QuestProgressModifierSystem.amount(ally,1)==2,"Stormwind and Shared Legacy should affect a nearby ally immediately at Banner activation.");ally.pos=warrior.pos+Vector2(main.WarriorData.SPACE.banner_radius+10.0,0);main.update_warrior_runtime(.1);TestSupport.check(errors,is_equal_approx(main.active_movement_multiplier(ally),1.0) and main.QuestProgressModifierSystem.amount(ally,1)==1,"Leaving the Banner aura should immediately remove Stormwind and Shared Legacy.");ally.pos=warrior.pos;warrior.warrior_runtime.banner_remaining=7.0;main.update_warrior_runtime(.1);TestSupport.check(errors,main.QuestProgressModifierSystem.amount(ally,1)==2,"Entering during the first eight Banner seconds should grant Shared Legacy.");warrior.warrior_runtime.banner_remaining=4.0;main.update_warrior_runtime(.1);TestSupport.check(errors,main.QuestProgressModifierSystem.amount(ally,1)==1 and float(warrior.warrior_runtime.banner_remaining)>0.0,"Shared Legacy should end after eight seconds while the 12-second Banner remains active.")

	main.load_warrior_test_build(warrior,1);warrior.pos=ally.pos;warrior.hp=warrior.max_hp-100.0;main.update_warrior_runtime(.1);var ironforge_sources:Array=warrior.temporary_armor_sources.filter(func(source):return str(source.get("id",""))=="warrior_banner:%s"%str(warrior.combat_id));TestSupport.check(errors,not ironforge_sources.is_empty() and is_equal_approx(float(ironforge_sources[0].armor),main.WarriorData.scaled(20.0,30)) and is_equal_approx(main.HealingReceivedModifierSystem.multiplier(warrior),1.6) and float(warrior.hp)>float(warrior.max_hp)-100.0,"Ironforge should scale from 20 and Glory should combine deterministically with Taunt for +60% healing received plus extra regeneration.")
	main.load_warrior_test_build(warrior,2);warrior.pos=ally.pos;main.update_warrior_runtime(.1);TestSupport.check(errors,is_equal_approx(main.AbilityPowerSystem.apply(100.0,warrior),110.0),"Dalaran should grant live +10% Ability Power through the shared ability pipeline.")

	main.load_warrior_test_build(warrior,4);warrior.pos=Vector2(300,400);boss.pos=warrior.pos+Vector2(100,0);far_enemy.pos=warrior.pos+Vector2(main.WarriorData.SPACE.banner_radius+100.0,0);boss.active_effects=[];far_enemy.active_effects=[];main.update_warrior_runtime(.1);TestSupport.check(errors,is_equal_approx(main.OutgoingDamageReductionSystem.multiplier(boss),.6) and is_equal_approx(main.OutgoingDamageReductionSystem.multiplier(far_enemy),1.0),"Demoralizing Shout should snapshot nearby enemies including Bosses for 40% reduced outgoing damage.");boss.pos=far_enemy.pos;far_enemy.pos=warrior.pos;main.update_warrior_runtime(.1);TestSupport.check(errors,is_equal_approx(main.OutgoingDamageReductionSystem.multiplier(boss),.6) and is_equal_approx(main.OutgoingDamageReductionSystem.multiplier(far_enemy),1.0),"Demoralizing's five-second snapshot should persist after leaving while later entrants are not added.")
	return errors
