extends RefCounted

const TestSupport=preload("res://tests/test_support.gd")
const WarriorData=preload("res://scripts/data/warrior_data.gd")
const WarriorSystem=preload("res://scripts/systems/warrior_system.gd")
const AbilitySlotSystem=preload("res://scripts/systems/ability_slot_system.gd")
const HealingReceivedModifierSystem=preload("res://scripts/systems/healing_received_modifier_system.gd")
const ArmorEffectivenessSystem=preload("res://scripts/systems/armor_effectiveness_system.gd")
const QuestProgressModifierSystem=preload("res://scripts/systems/quest_progress_modifier_system.gd")
const ForcedTargetSystem=preload("res://scripts/systems/forced_target_system.gd")
const AbilityPowerSystem=preload("res://scripts/systems/ability_power_system.gd")
const ArmorReductionSystem=preload("res://scripts/systems/armor_reduction_system.gd")
const OutgoingDamageReductionSystem=preload("res://scripts/systems/outgoing_damage_reduction_system.gd")
const ProgressionScopeSystem=preload("res://scripts/systems/progression_scope_system.gd")
const ShamanSystem=preload("res://scripts/systems/shaman_system.gd")
const GuardianSystem=preload("res://scripts/systems/guardian_system.gd")
const DruidSystem=preload("res://scripts/systems/druid_system.gd")
const RangerSystem=preload("res://scripts/systems/ranger_system.gd")
const SlayerSystem=preload("res://scripts/systems/slayer_system.gd")
const TemplarSystem=preload("res://scripts/systems/templar_system.gd")
const SentinelSystem=preload("res://scripts/systems/sentinel_system.gd")
const HuntsmanSystem=preload("res://scripts/systems/huntsman_system.gd")

static func unit(talents:Dictionary={},heroic:String="",level:int=1)->Dictionary:
	var hero:={"class":"Warrior","role":"Melee DPS","combat_id":"hero:warrior","combat_affiliation":"player","battle_index":0,"level":level,"hp":WarriorData.scaled(2220.0,level),"max_hp":WarriorData.scaled(2220.0,level),"health_regeneration":WarriorData.scaled(4.625,level),"armor":0.0,"threat_modifier":1.0,"pos":Vector2.ZERO,"active_effects":[],"selected_talents":talents,"selected_heroic_id":heroic,"base_basic_action_interval":.8,"ability_cds":[0.0,0.0,0.0,0.0,0.0]}
	WarriorSystem.initialize_runtime(hero,true,"test:warrior");return hero

static func enemy(id:String,category:String="standard")->Dictionary:
	return {"combat_id":id,"combat_affiliation":"enemy","target_category":category,"combat_tags":[category],"hp":2000.0,"max_hp":2000.0,"shield":0.0,"shield_sources":[],"pos":Vector2.ZERO,"active_effects":[]}

static func run()->Array:
	var errors:Array=[];var definition:=WarriorData.CLASS_DEFINITION
	TestSupport.check(errors,is_equal_approx(float(definition.base_health),2220.0) and is_equal_approx(float(definition.health_regeneration),4.625) and is_equal_approx(float(definition.base_power),74.0),"Warrior should preserve audited level-one Health, regeneration, and Basic Attack anchors.")
	TestSupport.check(errors,is_equal_approx(float(definition.basic_action_interval),.8) and is_equal_approx(float(definition.basic_action_range),1.25*float(WarriorData.SPACE.source_to_world)) and not bool(definition.uses_mana),"Warrior should use the audited melee cadence/range and no resource.")
	TestSupport.check(errors,is_equal_approx(float(definition.base_armor),0.0) and is_equal_approx(float(definition.threat_modifier),1.0) and str(definition.primary_role)=="Melee DPS" and str(definition.armor_family)=="plate","Warrior should retain 0 Armor, baseline Threat 1.0, Melee DPS identity, and Plate proficiency.")
	TestSupport.check(errors,is_equal_approx(WarriorData.scaled(2220.0,2),2308.8) and is_equal_approx(WarriorData.scaled(74.0,2),76.96),"Warrior Health and damage should use exact four-percent level scaling.")
	TestSupport.check(errors,WarriorData.TALENT_TIERS.size()==8 and WarriorData.TALENT_TIERS[3].option_ids.size()==2 and WarriorData.TEST_BUILDS.size()==6,"Warrior should expose eight exact tiers, the two-option Guild tier, and six representative builds.")
	var expected_talents:=["warrior_l9_1","warrior_l9_2","warrior_l9_3","warrior_l12_r1","warrior_l12_r2","warrior_l12_r3","warrior_l15_1","warrior_l15_2","warrior_l15_3","warrior_l18_1","warrior_l18_2","warrior_l21_1","warrior_l21_2","warrior_l21_3","warrior_l24_1","warrior_l24_2","warrior_l24_3","warrior_l27_r1","warrior_l27_r2","warrior_l27_r3","warrior_l30_1","warrior_l30_2","warrior_l30_3"];var actual_talents:Array=[];for tier in WarriorData.TALENT_TIERS:actual_talents.append_array(tier.option_ids)
	TestSupport.check(errors,actual_talents==expected_talents and WarriorData.TALENT_TIERS[6].heroic_requirements=={"warrior_l27_r1":"warrior_l12_r1","warrior_l27_r2":"warrior_l12_r2","warrior_l27_r3":"warrior_l12_r3"},"Warrior should register every approved talent exactly once and gate each Guild-27 upgrade to its matching specialization.")

	var base:=unit();base.warrior_runtime.heroic_strike_cooldown=0.0;var attack:=WarriorSystem.note_primary_basic_attack(base,enemy("standard"),{"resolved_damage":74.0,"critical":false},true)
	TestSupport.check(errors,bool(attack.heroic_strike) and is_equal_approx(float(attack.heroic_damage),125.0) and is_equal_approx(float(base.warrior_runtime.heroic_strike_cooldown),15.0),"A successful empowered primary attack should emit a separate 125 packet and then apply three seconds of CDR.")
	var scaled_strike:=unit({},"",10);scaled_strike.warrior_runtime.heroic_strike_cooldown=0.0;attack=WarriorSystem.note_primary_basic_attack(scaled_strike,enemy("scaled"),{"resolved_damage":WarriorData.scaled(74.0,10)},true);TestSupport.check(errors,is_equal_approx(float(attack.heroic_damage),WarriorData.scaled(125.0,10)),"Heroic Strike should scale independently from the primary Basic Attack packet.")
	var twin:=unit({"tier_2":"warrior_l12_r3"},"warrior_l12_r3");twin.warrior_runtime.heroic_strike_cooldown=0.0;attack=WarriorSystem.note_primary_basic_attack(twin,enemy("twin"),{"resolved_damage":55.5},true)
	TestSupport.check(errors,is_equal_approx(WarriorSystem.attack_interval(twin),.4) and is_equal_approx(WarriorSystem.basic_attack_amount(twin),55.5) and is_equal_approx(float(twin.warrior_runtime.heroic_strike_cooldown),11.0) and is_equal_approx(float(twin.warrior_runtime.twin_move_remaining),2.0) and str(twin.effective_role)=="Melee DPS","Twin Blades should double attack speed, reduce Basic Attack damage by 25%, apply seven total seconds of Heroic Strike CDR, and remain passive DPS.")
	var frenzy:=unit({"tier_1":"warrior_l9_2","tier_2":"warrior_l12_r3","tier_7":"warrior_l27_r3"},"warrior_l12_r3");frenzy.warrior_runtime.parry_remaining=1.0;WarriorSystem.note_parry_contact(frenzy);TestSupport.check(errors,is_equal_approx(WarriorSystem.heroic_strike_damage(frenzy),206.25),"Overpower and Frenzy should add their one-shot +40% and specialization +25% Heroic Strike modifiers without changing primary Basic Attack damage.")
	WarriorSystem.note_primary_basic_attack(frenzy,enemy("consume"),{"resolved_damage":55.5},true);TestSupport.check(errors,not bool(frenzy.warrior_runtime.overpower_armed) and is_equal_approx(WarriorSystem.heroic_strike_damage(frenzy),156.25),"Overpower should be consumed once while Frenzy remains active for later Heroic Strikes.")

	var maw:=unit({"tier_1":"warrior_l9_1","tier_3":"warrior_l15_1"});var contacts:=[enemy("a"),enemy("b","elite"),enemy("c","named"),enemy("d","boss"),enemy("e","summon"),enemy("f")];var plan:=WarriorSystem.lions_fang_plan(maw,contacts);WarriorSystem.note_lions_fang_cast(maw,plan)
	TestSupport.check(errors,int(plan.quest_contacts)==5 and is_equal_approx(float(plan.healing),35.0*5.0+245.0) and int(maw.warrior_runtime.lions_maw)==5,"Lion's Fang should cap quest contacts at five, heal each eligible contact independently, and use Lionheart Boss/summon values.")
	maw.warrior_runtime.lions_maw=25;plan=WarriorSystem.lions_fang_plan(maw,[enemy("slow")]);TestSupport.check(errors,is_equal_approx(float(plan.damage),325.0) and is_equal_approx(float(plan.slow),.5) and is_equal_approx(float(plan.slow_duration),2.0),"Completed Lion's Maw should add 175 level-one damage and improve the Slow to 50% for two seconds.")

	var parry:=unit({"tier_1":"warrior_l9_2","tier_7":"warrior_l27_r1"},"warrior_l12_r1");parry.warrior_runtime.taunt_cooldown=8.0;TestSupport.check(errors,WarriorSystem.cast_parry(parry),"Parry should spend an available charge.");var contact:=WarriorSystem.note_parry_contact(parry)
	TestSupport.check(errors,bool(contact.prevented) and bool(parry.warrior_runtime.overpower_armed) and is_equal_approx(float(parry.warrior_runtime.heroic_strike_cooldown),0.0) and is_equal_approx(float(parry.warrior_runtime.taunt_cooldown),7.0),"A Basic Attack contact during Parry should prevent damage, arm Overpower, and let Vigilance reduce Taunt.")
	var wall:=unit({"tier_4":"warrior_l18_1"});TestSupport.check(errors,int(wall.warrior_runtime.w_slot.max_charges)==1 and is_equal_approx(float(wall.warrior_runtime.w_slot.recharge_duration),5.0),"Shield Wall should replace Parry with one Protected charge recharging in five seconds.")

	var taunt:=unit({"tier_2":"warrior_l12_r1"},"warrior_l12_r1");TestSupport.check(errors,str(taunt.effective_role)=="Tank" and is_equal_approx(float(taunt.threat_modifier),1.5) and is_equal_approx(HealingReceivedModifierSystem.multiplier(taunt),1.1) and is_equal_approx(ArmorEffectivenessSystem.apply_positive(taunt,20.0),22.0),"Taunt should change effective role/threat and improve healing received and positive Armor effectiveness by 10% without changing max Health.")
	var smash:=unit({"tier_2":"warrior_l12_r2"},"warrior_l12_r2");TestSupport.check(errors,is_equal_approx(float(smash.max_hp),1998.0) and is_equal_approx(WarriorSystem.basic_attack_amount(smash),148.0),"Colossus Smash should reduce maximum Health by 10% and double Basic Attack damage without a regeneration penalty.")
	WarriorSystem.reset_encounter(smash,"test:warrior:next");TestSupport.check(errors,is_equal_approx(float(smash.max_hp),1998.0),"Starting a new encounter should not compound Colossus Smash's maximum-Health reduction.")
	HealingReceivedModifierSystem.apply(taunt,"mortal:a",-.4,4.0);HealingReceivedModifierSystem.apply(taunt,"mortal:b",-.4,4.0);TestSupport.check(errors,is_equal_approx(HealingReceivedModifierSystem.multiplier(taunt),.7),"Healing bonuses should add while duplicate healing reductions use the strongest source rather than stacking.")

	var high:=unit({"tier_1":"warrior_l9_3","tier_3":"warrior_l15_3"});high.warrior_runtime.encounter_progress={"high_weapon":50,"high_honors":5,"high_endurance":15};TestSupport.check(errors,is_equal_approx(WarriorSystem.high_reward_level_one(high),60.0) and is_equal_approx(WarriorSystem.basic_attack_amount(high),134.0),"Completing all High King objectives should grant +10 each and +30 final, for +60 level-one Basic Attack damage.")
	var shared:=unit();QuestProgressModifierSystem.apply(shared,"banner",2.0,8.0);TestSupport.check(errors,QuestProgressModifierSystem.amount(shared,3)==6,"Shared Legacy should double numeric combat-talent progress.")

	var summon:=enemy("summon","summon");summon.summoned_unit=true;summon.original_lifetime=25.0;summon.remaining_lifetime=10.0;var hunter:=unit({"tier_5":"warrior_l21_1"});var anti:=WarriorSystem.anti_summon(hunter,summon)
	TestSupport.check(errors,is_equal_approx(float(anti.damage),80.0) and is_equal_approx(float(anti.removed),1.0) and is_equal_approx(float(summon.remaining_lifetime),9.0),"Juggernaut should request 4% maximum-Health damage and remove 4% of original summon lifetime.")
	var shielded:=enemy("shield");shielded.shield=1500.0;shielded.shield_sources=[{"source_id":"test","amount":1500.0}];TestSupport.check(errors,is_equal_approx(WarriorSystem.shield_only_damage(shielded,1400.0),1400.0) and is_equal_approx(float(shielded.shield),100.0) and is_equal_approx(float(shielded.hp),2000.0),"Shattering bonus damage should consume shields only and never spill into Health.")

	var forced:=enemy("forced");ForcedTargetSystem.apply(forced,2,"taunt",1.25);TestSupport.check(errors,ForcedTargetSystem.preferred(forced)==2,"Forced targeting should select the Taunting Warrior, including for Boss-compatible profiles.");ForcedTargetSystem.update(forced,1.25);TestSupport.check(errors,ForcedTargetSystem.preferred(forced)==-1,"Forced targeting should expire exactly at its duration.")
	var banner:=unit({"tier_6":"warrior_l24_2","tier_8":"warrior_l30_3"});var activated:=WarriorSystem.update(banner,.01);TestSupport.check(errors,bool(activated.banner_activated) and str(banner.warrior_runtime.banner_type)=="ironforge" and is_equal_approx(float(banner.warrior_runtime.banner_remaining),12.0),"A selected banner should activate immediately and begin its 12-second aura/25-second cadence.")
	var power_target:={"ability_power_percent":.05,"active_effects":[{"ability_power_percent":.10,"remaining_duration":1.0}]};TestSupport.check(errors,is_equal_approx(AbilityPowerSystem.apply(100.0,power_target),115.0),"Dalaran-style active Ability Power should stack additively with ordinary Ability Power.")

	var baseline_q:=unit();var baseline_plan:=WarriorSystem.lions_fang_plan(baseline_q,[enemy("normal"),enemy("boss","boss"),enemy("summon_only","summon"),enemy("temporary","temporary_combat")]);TestSupport.check(errors,int(baseline_plan.quest_contacts)==2 and is_equal_approx(float(baseline_plan.damage),150.0) and is_equal_approx(float(baseline_plan.healing),175.0) and is_equal_approx(float(baseline_plan.slow),.35) and is_equal_approx(float(baseline_plan.slow_duration),1.5),"Baseline Lion's Fang should damage every category but heal only quest-valid contacts, using 35 normal and 140 Boss healing while excluding summon/temporary healing.")
	var scaled_q:=unit({},"",2);var scaled_plan:=WarriorSystem.lions_fang_plan(scaled_q,[enemy("scaled_normal"),enemy("scaled_boss","boss")]);TestSupport.check(errors,is_equal_approx(float(scaled_plan.damage),156.0) and is_equal_approx(float(scaled_plan.healing),182.0),"Lion's Fang damage and every contact-heal amount should scale by four percent per level.")
	var duplicate:=enemy("duplicate");var duplicate_plan:=WarriorSystem.lions_fang_plan(maw,[duplicate,duplicate,enemy("temp","temporary_combat"),enemy("summon_quest","summon")]);TestSupport.check(errors,int(duplicate_plan.quest_contacts)==1,"Lion's Maw should count a qualifying target once per cast and exclude summon and temporary-combat targets.")
	var maw_scope:=unit({"tier_1":"warrior_l9_1"});var maw_id:=str(maw_scope.warrior_runtime.encounter_id);WarriorSystem.note_lions_fang_cast(maw_scope,{"quest_contacts":3,"healing":0.0,"boss_healing":0.0,"summon_healing":0.0});ProgressionScopeSystem.room_transition(maw_scope.warrior_runtime,maw_id);TestSupport.check(errors,int(maw_scope.warrior_runtime.lions_maw)==3,"Lion's Maw progress should survive rooms within the same encounter.");WarriorSystem.reset_encounter(maw_scope,"test:maw:new");TestSupport.check(errors,int(maw_scope.warrior_runtime.lions_maw)==0,"Lion's Maw progress should reset for a new encounter.")

	var parry_charges:=unit();TestSupport.check(errors,int(parry_charges.warrior_runtime.w_slot.current_charges)==2 and is_equal_approx(float(parry_charges.warrior_runtime.w_slot.recharge_duration),10.0),"Baseline Parry should begin with two sequential charges and a ten-second recharge.");WarriorSystem.cast_parry(parry_charges);WarriorSystem.cast_parry(parry_charges);WarriorSystem.update(parry_charges,10.0);TestSupport.check(errors,int(parry_charges.warrior_runtime.w_slot.current_charges)==1 and is_equal_approx(float(parry_charges.warrior_runtime.parry_remaining),0.0),"Parry should last 1.25 seconds and restore sequential charges on its ten-second timer.")
	var repeated_overpower:=unit({"tier_1":"warrior_l9_2"});repeated_overpower.warrior_runtime.parry_remaining=1.0;WarriorSystem.note_parry_contact(repeated_overpower);WarriorSystem.note_parry_contact(repeated_overpower);TestSupport.check(errors,is_equal_approx(WarriorSystem.heroic_strike_damage(repeated_overpower),175.0),"Repeated Parry contacts should refresh and re-arm, never stack multiple Overpower bonuses onto one Heroic Strike.")

	var high_weapon:=unit({"tier_1":"warrior_l9_3"});WarriorSystem.note_primary_basic_attack(high_weapon,enemy("same_boss","boss"),{"resolved_damage":74.0},false);WarriorSystem.note_primary_basic_attack(high_weapon,enemy("same_boss","boss"),{"resolved_damage":74.0},false);WarriorSystem.note_primary_basic_attack(high_weapon,enemy("excluded_summon","summon"),{"resolved_damage":74.0},false);WarriorSystem.note_primary_basic_attack(high_weapon,enemy("excluded_temp","temporary_combat"),{"resolved_damage":74.0},false);TestSupport.check(errors,WarriorSystem.high_progress(high_weapon,"high_weapon")==2,"Weapon Mastery should count repeated successful attacks on one Boss and exclude summon/temporary targets.")
	var honor_target:=enemy("honor");WarriorSystem.note_damage_participation(high_weapon,honor_target,1.0);WarriorSystem.note_enemy_defeat(high_weapon,honor_target,0.0);TestSupport.check(errors,WarriorSystem.high_progress(high_weapon,"high_honors")==1,"Battle Honors should use recent qualifying damage participation.");var expired_target:=enemy("expired");WarriorSystem.note_damage_participation(high_weapon,expired_target,1.0);WarriorSystem.update(high_weapon,5.1);WarriorSystem.note_enemy_defeat(high_weapon,expired_target,0.0);TestSupport.check(errors,WarriorSystem.high_progress(high_weapon,"high_honors")==1,"Battle Honors should not grant credit outside the deterministic participation window.")
	var endurance:=unit({"tier_1":"warrior_l9_3","tier_3":"warrior_l15_1"});var endurance_plan:=WarriorSystem.lions_fang_plan(endurance,[enemy("end_a"),enemy("end_b"),enemy("end_c","boss")]);WarriorSystem.note_lions_fang_cast(endurance,endurance_plan);TestSupport.check(errors,WarriorSystem.high_progress(endurance,"high_endurance")==1,"Any number of legitimate Lion's Fang healing contacts should grant at most one Endurance event per cast, including overhealing.")
	var second_wind:=unit({"tier_1":"warrior_l9_3","tier_3":"warrior_l15_2"});second_wind.warrior_runtime.heroic_strike_cooldown=0.0;var sustain:=WarriorSystem.note_primary_basic_attack(second_wind,enemy("second"),{"resolved_damage":74.0},true);TestSupport.check(errors,is_equal_approx(float(sustain.second_wind),22.2) and WarriorSystem.high_progress(second_wind,"high_endurance")==0,"Second Wind should request exactly 1% current maximum Health only on Heroic Strike and never advance Endurance.");sustain=WarriorSystem.note_primary_basic_attack(second_wind,enemy("ordinary"),{"resolved_damage":74.0},false);TestSupport.check(errors,is_equal_approx(float(sustain.second_wind),0.0),"Ordinary Basic Attacks should not trigger Second Wind.")
	var victory:=unit({"tier_1":"warrior_l9_3","tier_3":"warrior_l15_3"});victory.warrior_runtime.victory_cooldown=0.0;sustain=WarriorSystem.note_primary_basic_attack(victory,enemy("victory"),{"resolved_damage":74.0},false);TestSupport.check(errors,bool(sustain.victory) and is_equal_approx(float(sustain.victory_heal),350.0) and is_equal_approx(float(victory.warrior_runtime.victory_cooldown),30.0),"Victory Rush should prime every 30 seconds and heal a scaled 350 on the next successful primary attack.");WarriorSystem.add_progress(victory,"high_endurance",1);WarriorSystem.note_enemy_defeat(victory,enemy("nearby"),float(WarriorData.SPACE.victory_radius));TestSupport.check(errors,WarriorSystem.high_progress(victory,"high_endurance")==1 and is_equal_approx(float(victory.warrior_runtime.victory_cooldown),20.0),"Victory Rush should contribute one Endurance event through its live healing hook and nearby deaths should reduce its cooldown by ten seconds.")

	TestSupport.check(errors,is_equal_approx(float(taunt.max_hp),2220.0) and is_equal_approx(ArmorEffectivenessSystem.apply_positive(taunt,-20.0),-20.0),"Taunt must add no maximum Health and must not amplify negative Armor.")
	var taunt_heals:=unit({"tier_2":"warrior_l12_r1","tier_3":"warrior_l15_2"},"warrior_l12_r1");taunt_heals.warrior_runtime.heroic_strike_cooldown=0.0;sustain=WarriorSystem.note_primary_basic_attack(taunt_heals,enemy("tank_sustain"),{"resolved_damage":74.0},true);TestSupport.check(errors,is_equal_approx(float(sustain.second_wind),22.2) and is_equal_approx(float(sustain.second_wind)*HealingReceivedModifierSystem.multiplier(taunt_heals),24.42),"Taunt's healing-received bonus should modify Second Wind through the shared pipeline, not its native percentage.")
	TestSupport.check(errors,is_equal_approx(float(smash.health_regeneration),4.625) and str(smash.effective_role)=="Melee DPS","Colossus Smash should preserve regeneration and remain Melee DPS.");var scaled_smash:=unit({"tier_2":"warrior_l12_r2"},"warrior_l12_r2",2);var armored:=enemy("armored");armored.armor=100.0;ArmorReductionSystem.apply(armored,"huntsman",30.0,5.0);ArmorReductionSystem.apply(armored,"warrior",WarriorData.scaled(25.0,2),3.0);TestSupport.check(errors,is_equal_approx(ArmorReductionSystem.effective(armored),30.0),"Colossus Smash's scaled Armor reduction should share the strongest-source rule with Huntsman instead of stacking.");ArmorReductionSystem.apply(armored,"warrior",WarriorData.scaled(35.0,2),3.0);TestSupport.check(errors,is_equal_approx(ArmorReductionSystem.effective(armored),36.4),"The stronger source-aware Armor reduction should win deterministically.")
	var high_colossus:=unit({"tier_1":"warrior_l9_3","tier_2":"warrior_l12_r2"},"warrior_l12_r2");high_colossus.warrior_runtime.encounter_progress={"high_weapon":50,"high_honors":5,"high_endurance":15};var high_twin:=unit({"tier_1":"warrior_l9_3","tier_2":"warrior_l12_r3"},"warrior_l12_r3");high_twin.warrior_runtime.encounter_progress=high_colossus.warrior_runtime.encounter_progress.duplicate(true);TestSupport.check(errors,is_equal_approx(WarriorSystem.basic_attack_amount(high_colossus),268.0) and is_equal_approx(WarriorSystem.basic_attack_amount(high_twin),100.5),"High King's +60 basis should be applied before Colossus x2 or Twin Blades x0.75 modifiers.")

	var permanent:=enemy("permanent","summon");permanent.summoned_unit=true;var permanent_anti:=WarriorSystem.anti_summon(hunter,permanent);TestSupport.check(errors,is_equal_approx(float(permanent_anti.damage),80.0) and is_equal_approx(float(permanent_anti.removed),0.0),"Juggernaut should damage permanent summons without inventing a lifetime.");var short:=enemy("short","summon");short.summoned_unit=true;short.original_lifetime=100.0;short.remaining_lifetime=2.0;var short_anti:=WarriorSystem.anti_summon(hunter,short);TestSupport.check(errors,bool(short_anti.despawned) and is_equal_approx(float(short_anti.removed),2.0) and float(short.hp)<=0.0,"Juggernaut lifetime removal should clamp and deterministically despawn a short-lived summon.");TestSupport.check(errors,is_equal_approx(float(WarriorSystem.anti_summon(hunter,enemy("ordinary")).damage),0.0) and is_equal_approx(float(WarriorSystem.anti_summon(hunter,enemy("boss_not_summon","boss")).damage),0.0),"Juggernaut should not add percentage damage to ordinary targets or Bosses.")
	HealingReceivedModifierSystem.update(taunt,4.0);TestSupport.check(errors,is_equal_approx(HealingReceivedModifierSystem.multiplier(taunt),1.1),"Mortal Strike sources should expire after four seconds while Taunt's permanent healing bonus remains.")

	TestSupport.check(errors,WarriorSystem.banner_type(unit({"tier_6":"warrior_l24_1"}))=="stormwind" and WarriorSystem.banner_type(unit({"tier_6":"warrior_l24_2"}))=="ironforge" and WarriorSystem.banner_type(unit({"tier_6":"warrior_l24_3"}))=="dalaran","Each Guild-24 choice should map to exactly one automatic Banner aura.");WarriorSystem.update(banner,12.0);TestSupport.check(errors,is_equal_approx(float(banner.warrior_runtime.banner_remaining),0.0) and is_equal_approx(float(banner.warrior_runtime.banner_cooldown),13.0),"A Banner should end after 12 seconds while retaining the 25-second activation cadence.");WarriorSystem.update(banner,13.0);TestSupport.check(errors,is_equal_approx(float(banner.warrior_runtime.banner_remaining),12.0),"The next automatic Banner should begin exactly 25 seconds after activation.")
	var reduced_enemy:=enemy("reduced");OutgoingDamageReductionSystem.apply(reduced_enemy,"small",.20,5.0);OutgoingDamageReductionSystem.apply(reduced_enemy,"warrior",.40,5.0);TestSupport.check(errors,is_equal_approx(OutgoingDamageReductionSystem.multiplier(reduced_enemy),.60),"Demoralizing Shout should use the strongest source-aware outgoing-damage reduction rather than stack reductions.")

	QuestProgressModifierSystem.apply(shared,"banner_two",2.0,8.0);TestSupport.check(errors,QuestProgressModifierSystem.amount(shared,5)==10,"Overlapping Shared Legacy sources should remain 2x, including larger numeric progress events.");QuestProgressModifierSystem.update(shared,8.0);TestSupport.check(errors,QuestProgressModifierSystem.amount(shared,1)==1,"Shared Legacy should stop modifying progress after its eight-second window.")
	var shared_high:=unit({"tier_1":"warrior_l9_3"});QuestProgressModifierSystem.apply(shared_high,"banner",2.0,8.0);WarriorSystem.add_progress(shared_high,"high_weapon",1);TestSupport.check(errors,WarriorSystem.high_progress(shared_high,"high_weapon")==2 and is_equal_approx(WarriorSystem.high_reward_level_one(shared_high),0.0),"Shared Legacy should double High King's numeric progress without duplicating completion rewards.");var shared_maw:=unit({"tier_1":"warrior_l9_1"});QuestProgressModifierSystem.apply(shared_maw,"banner",2.0,8.0);WarriorSystem.note_lions_fang_cast(shared_maw,{"quest_contacts":5,"healing":0.0,"boss_healing":0.0,"summon_healing":0.0});TestSupport.check(errors,int(shared_maw.warrior_runtime.lions_maw)==10,"Shared Legacy should double Lion's Maw contact progress.")
	var shaman:={"class":"Shaman","combat_id":"hero:shaman","level":1,"hp":2000.0,"max_hp":2000.0,"selected_talents":{"tier_1":"shaman_l9_2"},"ability_cds":[0.0,0.0,0.0,0.0,0.0]};ShamanSystem.initialize_runtime(shaman,false,{},"test:shared");QuestProgressModifierSystem.apply(shaman,"warrior_banner",2.0,8.0);ShamanSystem.note_chain_cast(shaman,"primary",["a","b","c"]);TestSupport.check(errors,ShamanSystem.encounter_progress(shaman,"crash")==2 and ShamanSystem.mastery_progress(shaman,"shaman_l9_2")==2,"Shared Legacy should double both another class's encounter quest and Shaman's persistent combat-talent mastery through one numeric event.")
	var guardian:={"class":"Guardian","combat_id":"hero:guardian","level":1,"selected_talents":{},"ability_cds":[0.0,0.0,0.0,0.0,0.0]};GuardianSystem.initialize_runtime(guardian);QuestProgressModifierSystem.apply(guardian,"banner",2.0,8.0);GuardianSystem.add_quest(guardian,5,"shared",0.0)
	var druid:={"class":"Druid","combat_id":"hero:druid","level":1,"selected_talents":{"tier_1":"druid_l9_2"},"ability_cds":[0.0,0.0,0.0,0.0,0.0]};DruidSystem.initialize_runtime(druid);QuestProgressModifierSystem.apply(druid,"banner",2.0,8.0);DruidSystem.note_root_result(druid,enemy("druid_quest"),true)
	var ranger:={"class":"Ranger","combat_id":"hero:ranger","level":1,"selected_talents":{"tier_1":"ranger_l9_3"},"ability_cds":[0.0,0.0,0.0,0.0,0.0],"base_basic_action_interval":1.0};RangerSystem.initialize_runtime(ranger);QuestProgressModifierSystem.apply(ranger,"banner",2.0,8.0);RangerSystem.on_basic_attack_resolved(ranger,{"resolved_damage":1.0},false,false)
	var slayer:={"class":"Slayer","combat_id":"hero:slayer","level":1,"selected_talents":{"tier_2":"slayer_l12_3"},"ability_cds":[0.0,0.0,0.0,0.0,0.0]};SlayerSystem.initialize_runtime(slayer);QuestProgressModifierSystem.apply(slayer,"banner",2.0,8.0);SlayerSystem.note_sweep(slayer,[enemy("slayer_quest")])
	var templar:={"class":"Templar","combat_id":"hero:templar","level":1,"selected_talents":{"tier_1":"templar_l9_3"},"ability_cds":[0.0,0.0,0.0,0.0,0.0]};TemplarSystem.initialize_runtime(templar);QuestProgressModifierSystem.apply(templar,"banner",2.0,8.0);TemplarSystem.note_successful_basic_attack(templar,enemy("templar_quest"))
	var sentinel:={"class":"Sentinel","combat_id":"hero:sentinel","level":1,"selected_talents":{},"ability_cds":[0.0,0.0,0.0,0.0,0.0]};SentinelSystem.initialize_runtime(sentinel);QuestProgressModifierSystem.apply(sentinel,"banner",2.0,8.0);SentinelSystem.note_e_hit(sentinel,enemy("sentinel_quest"))
	var huntsman:={"class":"Huntsman","combat_id":"hero:huntsman"};QuestProgressModifierSystem.apply(huntsman,"banner",2.0,8.0)
	TestSupport.check(errors,int(guardian.guardian_runtime.quest_stacks)==10 and int(druid.druid_runtime.vengeful_quest_stacks)==2 and int(ranger.ranger_runtime.basic_attack_quest)==2 and int(slayer.slayer_runtime.unbound_progress)==2 and int(templar.templar_runtime.protector_stacks)==2 and int(sentinel.sentinel_runtime.e_quest_stacks)==2 and HuntsmanSystem.quest_amount(huntsman,1)==2,"Shared Legacy should route every registered class combat-talent quest through the common strongest numeric multiplier.")
	return errors
