extends RefCounted
const VitalistData=preload("res://scripts/data/vitalist_data.gd")
const VitalistSystem=preload("res://scripts/systems/vitalist_system.gd")
const AbilitySlotSystem=preload("res://scripts/systems/ability_slot_system.gd")
const TestSupport=preload("res://tests/test_support.gd")

static func hero(talents:Dictionary={},heroic:String="vitalist_l15_r1",level:int=1,id:String="hero:vitalist")->Dictionary:
	var unit:={"class":"Vitalist","combat_id":id,"level":level,"hp":VitalistData.scaled(float(VitalistData.VALUES.health),level),"max_hp":VitalistData.scaled(float(VitalistData.VALUES.health),level),"selected_talents":talents,"selected_heroic_id":heroic,"ability_cds":[0.0,0.0,0.0,0.0,0.0],"active_effects":[]};VitalistSystem.initialize_runtime(unit,true,"test");return unit

static func run()->Array:
	var errors:Array=[];var definition:=VitalistData.CLASS_DEFINITION
	TestSupport.check(errors,str(definition.primary_role)=="Healer" and not bool(definition.uses_mana) and str(definition.resource_id)=="","Vitalist should be a resource-free Healer.")
	TestSupport.check(errors,is_equal_approx(float(definition.base_health),1835.0) and is_equal_approx(float(definition.base_power),261.0) and is_equal_approx(float(definition.basic_action_interval),1.5) and is_equal_approx(float(definition.basic_action_range),1.5*VitalistData.SOURCE_TO_WORLD),"Vitalist should retain Stukov's strong, slow melee chassis.")
	TestSupport.check(errors,VitalistData.TALENT_TIERS.size()==8 and VitalistData.TALENT_TIERS.reduce(func(total,tier):return total+tier.option_ids.size(),0)==22,"Vitalist should expose eight tiers and twenty-two choices.")
	var baseline:=hero();var q:=VitalistSystem.create_q_cast(baseline,"ally:a");TestSupport.check(errors,is_equal_approx(float(q.remaining),4.5) and is_equal_approx(float(q.spread),.75) and str(q.owner_id)=="hero:vitalist","Q should use source duration/spread timing and explicit owner identity.")
	TestSupport.check(errors,VitalistSystem.can_spread_to(baseline,q,"ally:b") and not VitalistSystem.spread_q(baseline,q,"ally:b").is_empty() and not VitalistSystem.can_spread_to(baseline,q,"ally:b"),"One baseline Q cast should infect each ally only once.")
	var other:=hero({},"vitalist_l15_r1",1,"hero:other");VitalistSystem.create_q_cast(other,"ally:a");var own_snapshot:=VitalistSystem.d_snapshot(baseline);TestSupport.check(errors,own_snapshot.q.size()==2 and other.vitalist_runtime.q_infections.size()==1,"Vitalist ownership should isolate Q snapshots across casters.")
	VitalistSystem.apply_w(baseline,"enemy:a");TestSupport.check(errors,is_equal_approx(VitalistSystem.w_slow(baseline.vitalist_runtime.w_infections["enemy:a"]),.05),"W should begin at 5% Slow.");baseline.vitalist_runtime.w_infections["enemy:a"].age=3.0;TestSupport.check(errors,is_equal_approx(VitalistSystem.w_slow(baseline.vitalist_runtime.w_infections["enemy:a"]),.50),"W should ramp to 50% Slow over three seconds.")
	var d_plan:=VitalistSystem.detonate(baseline);TestSupport.check(errors,d_plan.q.size()==2 and d_plan.w.size()==1 and baseline.vitalist_runtime.q_infections.is_empty() and baseline.vitalist_runtime.w_infections.is_empty(),"Baseline D should snapshot and remove only its owner's Q/W infections.")
	var fetid:=hero({"tier_1":"vitalist_l9_1"});for i in 15:VitalistSystem.apply_w(fetid,"enemy:%d"%i,true)
	TestSupport.check(errors,bool(fetid.vitalist_runtime.quest.complete) and is_equal_approx(VitalistSystem.w_cooldown(fetid),5.0) and is_equal_approx(float(fetid.range),float(VitalistData.SPACE.fetid_range)),"Fetid Touch should be permanent ranged mode and complete its 15-hit encounter quest for five-second W cooldown.")
	var reactive:=hero({"tier_1":"vitalist_l9_3","tier_8":"vitalist_l30_3"});reactive.hp=reactive.max_hp*.49;VitalistSystem.detonate(reactive);var before:=float(reactive.vitalist_runtime.d_slot.timers[0]);VitalistSystem.advance(reactive,1.0);TestSupport.check(errors,is_equal_approx(before-float(reactive.vitalist_runtime.d_slot.timers[0]),2.0),"Reactive Ballistospores should double active D recharge below 50% Health without refilling all charges.")
	var one_good:=hero({"tier_2":"vitalist_l12_1"});one_good.ability_cds[0]=10.0;var oq:=VitalistSystem.create_q_cast(one_good,"a");var sibling:=VitalistSystem.spread_q(one_good,oq,"b");VitalistSystem.spread_q(one_good,oq,"c");VitalistSystem.spread_q(one_good,sibling,"d");TestSupport.check(errors,is_equal_approx(float(one_good.ability_cds[0]),8.0),"One Good Spread should remove two seconds only once across every sibling of the original cast.")
	var quest_generated:=hero({"tier_1":"vitalist_l9_1"});VitalistSystem.apply_w(quest_generated,"enemy:auto",true,false);TestSupport.check(errors,int(quest_generated.vitalist_runtime.quest.progress)==0 and int(quest_generated.vitalist_runtime.telemetry.w_casts)==0,"Talent-generated replacement Pustules must not masquerade as manual W casts or advance Fetid Touch.")
	var targeted_pox:=hero({"tier_4":"vitalist_l18_3","tier_6":"vitalist_l24_3"});VitalistSystem.create_q_cast(targeted_pox,"a");var tp:=VitalistSystem.detonate(targeted_pox);TestSupport.check(errors,bool(tp.targeted) and targeted_pox.vitalist_runtime.q_infections.size()==1 and is_equal_approx(float(targeted_pox.vitalist_runtime.q_infections[0].remaining),7.5) and is_equal_approx(float(targeted_pox.vitalist_runtime.d_slot.recharge_duration),7.0),"Targeted Excision plus Pox should yield full Q duration plus three seconds and seven-second spent-D recharge.")
	var targeted_two:=hero({"tier_4":"vitalist_l18_3"});VitalistSystem.create_q_cast(targeted_two,"a");VitalistSystem.create_q_cast(targeted_two,"b");TestSupport.check(errors,not bool(VitalistSystem.detonate(targeted_two).targeted),"Targeted Excision must not trigger for two Q infections.")
	var long_pitch:=hero({"tier_4":"vitalist_l18_1"});VitalistSystem.apply_w(long_pitch,"a");VitalistSystem.apply_w(long_pitch,"b");var lp:=VitalistSystem.detonate(long_pitch);TestSupport.check(errors,lp.w.size()==2 and is_equal_approx(float(long_pitch.vitalist_runtime.long_pitch_remaining),4.0),"The Long Pitch should activate once from a two-W D snapshot.")
	var perfect_long:=hero({"tier_4":"vitalist_l18_1","tier_8":"vitalist_l30_3"});VitalistSystem.apply_w(perfect_long,"a");VitalistSystem.apply_w(perfect_long,"b");VitalistSystem.detonate(perfect_long);var perfect_before:=float(perfect_long.vitalist_runtime.d_slot.timers[0]);VitalistSystem.advance(perfect_long,1.0);TestSupport.check(errors,is_equal_approx(perfect_before-float(perfect_long.vitalist_runtime.d_slot.timers[0]),2.0),"The Long Pitch should accelerate Perfect Strain's active sequential recharge.")
	var growing:=hero({"tier_4":"vitalist_l18_2","tier_6":"vitalist_l24_3"});var gq:=VitalistSystem.create_q_cast(growing,"a");VitalistSystem.begin_arm(growing,Vector2.ZERO);TestSupport.check(errors,VitalistSystem.grow_q_in_arm(growing,"a") and not VitalistSystem.grow_q_in_arm(growing,"a") and is_equal_approx(float(gq.remaining),7.0),"Growing Infestation should extend each recipient once per E cast.");VitalistSystem.detonate(growing);TestSupport.check(errors,is_equal_approx(float(growing.vitalist_runtime.q_infections[0].remaining),10.0),"Growing Infestation and Pox should both extend without a cap.")
	var virulent:=hero({"tier_5":"vitalist_l21_2"});var vq:=VitalistSystem.create_q_cast(virulent,"a");TestSupport.check(errors,not VitalistSystem.spread_q(virulent,vq,"b",true).is_empty() and not VitalistSystem.spread_q(virulent,vq,"b",true).is_empty() and VitalistSystem.spread_q(virulent,vq,"b",true).is_empty(),"Virulent Reaction should permit exactly two same-cast infections for an ally inside E.")
	var carrier:=hero({"tier_6":"vitalist_l24_2"});var cq:=VitalistSystem.create_q_cast(carrier,"a");for i in 3:TestSupport.check(errors,not VitalistSystem.spread_q(carrier,cq,"hero:vitalist").is_empty(),"Universal Carrier should allow repeat spread through Vitalist.")
	var hungers:=hero({"tier_5":"vitalist_l21_1"});VitalistSystem.begin_arm(hungers,Vector2.ZERO);hungers.ability_cds[2]=10.0;TestSupport.check(errors,not VitalistSystem.note_arm_contacts(hungers,5) and VitalistSystem.note_arm_contacts(hungers,3) and is_equal_approx(float(hungers.ability_cds[2]),0.0),"It Hungers should reset E at eight capped qualifying damage contacts once per channel.")
	var controlled:=hero({"tier_7":"vitalist_l27_r1"});TestSupport.check(errors,int(controlled.vitalist_runtime.r_slot.current_charges)==3 and VitalistSystem.begin_swipe(controlled),"Controlled Chaos should start with three shared sequential R charges.")
	var perfect:=hero({"tier_8":"vitalist_l30_3"});TestSupport.check(errors,int(perfect.vitalist_runtime.d_slot.current_charges)==2 and not VitalistSystem.detonate(perfect).is_empty() and VitalistSystem.detonate(perfect).is_empty(),"Perfect Strain should provide two D charges with a two-second recast lockout.");VitalistSystem.advance(perfect,2.0);TestSupport.check(errors,not VitalistSystem.detonate(perfect).is_empty() and int(perfect.vitalist_runtime.d_slot.current_charges)==0,"Perfect Strain should consume the second stored charge after lockout while recharge remains sequential.")
	return errors
