extends RefCounted
const VanguardData=preload("res://scripts/data/vanguard_data.gd")
const VanguardSystem=preload("res://scripts/systems/vanguard_system.gd")
const AbilitySlotSystem=preload("res://scripts/systems/ability_slot_system.gd")
const StatusEffectSystem=preload("res://scripts/systems/status_effect_system.gd")
const BlockChargeSystem=preload("res://scripts/systems/block_charge_system.gd")
const TestSupport=preload("res://tests/test_support.gd")

static func hero(talents:Dictionary={},heroic:String="vanguard_l15_r1",level:int=1)->Dictionary:
	var unit:={"class":"Vanguard","combat_id":"hero:vanguard","combat_affiliation":"player","combat_team":"player","level":level,"pos":Vector2.ZERO,"hp":VanguardData.scaled(float(VanguardData.VALUES.health),level),"max_hp":VanguardData.scaled(float(VanguardData.VALUES.health),level),"selected_talents":talents,"selected_heroic_id":heroic,"ability_cds":[0.0,0.0,0.0,0.0,0.0],"active_effects":[],"temporary_armor_sources":[]}
	VanguardSystem.initialize_runtime(unit,true,"test:encounter");return unit

static func run()->Array:
	var errors:Array=[];var definition:=VanguardData.CLASS_DEFINITION
	TestSupport.check(errors,str(definition.primary_role)=="Tank" and not bool(definition.uses_mana) and is_equal_approx(float(definition.threat_modifier),1.5),"Vanguard should be a resource-free Tank with 1.5 Threat.")
	TestSupport.check(errors,is_equal_approx(float(definition.base_health),2280.0) and is_equal_approx(float(definition.base_power),99.0) and is_equal_approx(float(definition.basic_action_interval),.8),"Vanguard chassis should match current E.T.C. source values.")
	TestSupport.check(errors,VanguardData.TALENT_TIERS.size()==8 and VanguardData.TALENT_TIERS.reduce(func(total,tier):return total+tier.option_ids.size(),0)==22,"Vanguard should expose eight tiers and twenty-two mapped choices.")
	var baseline:=hero();var q:=VanguardSystem.q_plan(baseline,7);TestSupport.check(errors,is_equal_approx(float(q.damage),105.0) and int(q.contacts)==5 and is_equal_approx(float(q.stun),1.25),"Powerslide should use 105 damage, a 1.25-second Stun, and the shared five-contact cap.")
	baseline.ability_cds[0]=12.0;TestSupport.check(errors,is_equal_approx(VanguardSystem.finish_q(baseline,0),0.0),"Baseline Powerslide should not receive miss cooldown reduction.")
	var surfer:=hero({"tier_2":"vanguard_l12_1"});surfer.ability_cds[0]=12.0;VanguardSystem.q_plan(surfer,0);TestSupport.check(errors,bool(VanguardSystem.q_plan(surfer,0).cross_terrain) and is_equal_approx(VanguardSystem.finish_q(surfer,0),6.0) and is_equal_approx(float(surfer.ability_cds[0]),6.0),"Crowd Surfer should cross terrain and remove six seconds after a zero-contact Q.")
	var wall:=hero({"tier_2":"vanguard_l12_3"});var wall_q:=VanguardSystem.q_plan(wall,1);TestSupport.check(errors,bool(wall_q.push) and is_equal_approx(VanguardSystem.movement_multiplier(wall),1.2),"Wall of Sound should push and grant 20% movement speed once per cast.")
	var loud:=hero({"tier_2":"vanguard_l12_2"});var loud_w:=VanguardSystem.w_plan(loud,["a"]);TestSupport.check(errors,is_equal_approx(float(loud_w.radius),float(VanguardData.SPACE.w_radius)*1.5) and is_equal_approx(float(loud_w.displacement),float(VanguardData.SPACE.w_displacement)*1.5),"Loud Speakers should multiply both radius and displacement by 1.5.")
	var pinball:=hero({"tier_4":"vanguard_l18_1"});VanguardSystem.mark_pinball(pinball,"a");var pinball_w:=VanguardSystem.w_plan(pinball,["a","b"]);TestSupport.check(errors,pinball_w.empowered==["a"] and not pinball.vanguard_runtime.pinball.has("a") and is_equal_approx(float(VanguardData.VALUES.pinball_bonus),3.0),"Pinball Wizard should be owner/target scoped, last two seconds, and consume for 300% additional damage.")
	var mic:=hero({"tier_5":"vanguard_l21_1"});mic.ability_cds[1]=10.0;VanguardSystem.w_plan(mic,["a","b","c"]);TestSupport.check(errors,is_equal_approx(float(mic.ability_cds[1]),4.0),"Mic Check should remove six seconds once at two or more contacts.")
	var nightmare:=hero({"tier_6":"vanguard_l24_3"});TestSupport.check(errors,int(nightmare.vanguard_runtime.e_slot.current_charges)==3 and VanguardSystem.spend_overpower(nightmare) and not VanguardSystem.spend_overpower(nightmare),"Overpowering Nightmare should begin with three charges and enforce a two-second lockout.");VanguardSystem.advance(nightmare,2.0);TestSupport.check(errors,VanguardSystem.spend_overpower(nightmare) and int(nightmare.vanguard_runtime.e_slot.current_charges)==1,"A second Overpower charge should be available after the lockout while sequential recharge continues.")
	var performance:=hero({"tier_1":"vanguard_l9_1"});var stunned:={"active_effects":[]};StatusEffectSystem.apply_source_control(stunned,"ally","stun",1.0);TestSupport.check(errors,VanguardSystem.note_basic_attack(performance,stunned,true) and is_equal_approx(float(stunned.active_effects[0].remaining_duration),1.25),"Stunning Performance should extend an existing any-source Stun by 0.25 seconds.");var unstunned:={"active_effects":[]};TestSupport.check(errors,not VanguardSystem.note_basic_attack(performance,unstunned,true) and unstunned.active_effects.is_empty(),"Stunning Performance should never create a Stun.")
	var prog:=hero({"tier_1":"vanguard_l9_2"});for index in range(20):VanguardSystem.note_stun(prog,"Q","enemy:%d"%index,true)
	TestSupport.check(errors,bool(prog.vanguard_runtime.quest.complete) and int(prog.vanguard_runtime.quest.progress)==20 and prog.vanguard_runtime.healing_areas.size()==1,"Prog Rock should complete at twenty Q/E Stuns and the completing Stun should create its first independent healing area.");VanguardSystem.note_stun(prog,"Mosh","enemy:next",true);TestSupport.check(errors,prog.vanguard_runtime.healing_areas.size()==2,"Each later qualifying Vanguard Stun should create an overlapping healing instance.")
	var block:=hero({"tier_1":"vanguard_l9_3"});var block_commit:=VanguardSystem.commit_ability(block,false);BlockChargeSystem.grant(block,1,2);BlockChargeSystem.grant(block,5,2);TestSupport.check(errors,bool(block_commit.block_party) and BlockChargeSystem.charges(block)==2,"Block Party should use the shared two-charge Block system.")
	var rockstar:=hero();var basic:=VanguardSystem.commit_ability(rockstar,false);var heroic:=VanguardSystem.commit_ability(rockstar,true);TestSupport.check(errors,is_equal_approx(float(basic.armor),25.0) and is_equal_approx(float(heroic.armor),50.0) and is_equal_approx(float(heroic.duration),2.0),"Rockstar should grant scaled 25/50 Level-1 Universal Armor for two seconds.")
	var horde:=hero({"tier_8":"vanguard_l30_2"});TestSupport.check(errors,is_equal_approx(float(VanguardSystem.commit_ability(horde,false).armor),50.0) and is_equal_approx(float(VanguardSystem.commit_ability(horde,true).armor),75.0),"Power of the Horde should replace Rockstar with party 50/75 values.")
	var hammer:=hero({"tier_4":"vanguard_l18_2"});TestSupport.check(errors,is_equal_approx(VanguardSystem.basic_attack_multiplier(hammer,stunned),1.12) and is_equal_approx(VanguardSystem.basic_attack_multiplier(hammer,unstunned),1.0),"Hammer-On should add exactly 12% against a currently Stunned enemy.")
	var echo:=hero({"tier_4":"vanguard_l18_3"});VanguardSystem.commit_ability(echo,false);var immediate:=VanguardSystem.advance(echo,0.0);var delayed:=VanguardSystem.advance(echo,2.0);TestSupport.check(errors,immediate.any(func(event):return event.kind=="echo") and delayed.any(func(event):return event.kind=="echo"),"Echo Pedal should schedule ordinary-damage pulses at cast time and two seconds later.")
	var mosh:=hero({"tier_7":"vanguard_l27_r1"},"vanguard_l15_r1");mosh.ability_cds[0]=9.0;TestSupport.check(errors,VanguardSystem.begin_heroic(mosh,"vanguard_l15_r1") and is_equal_approx(float(mosh.ability_cds[3]),120.0) and is_equal_approx(float(mosh.ability_cds[0]),0.0),"Tour Bus Mosh should use 120 seconds and immediately refresh Q.");VanguardSystem.advance(mosh,.75);VanguardSystem.activate_heroic(mosh);TestSupport.check(errors,VanguardSystem.tour_bus_slide(mosh) and is_equal_approx(float(mosh.vanguard_runtime.mosh.remaining),6.0),"Tour Bus Q should add two seconds without cancelling Mosh.")
	var lightning:=hero({"tier_7":"vanguard_l27_r2"},"vanguard_l15_r2");VanguardSystem.begin_heroic(lightning,"vanguard_l15_r2");VanguardSystem.advance(lightning,.5);VanguardSystem.activate_heroic(lightning);TestSupport.check(errors,is_equal_approx(float(lightning.ability_cds[3]),90.0) and is_equal_approx(float(lightning.vanguard_runtime.lightning.duration),12.0) and is_equal_approx(float(VanguardData.VALUES.hellstorm_slow_max),.8),"Hellstorm should produce a 12-second channel and an 80% source-owned Slow cap.")
	var death:=hero({"tier_8":"vanguard_l30_3"},"vanguard_l15_r1");TestSupport.check(errors,VanguardSystem.try_death_metal(death,true) and not death.vanguard_runtime.lightning.is_empty() and is_equal_approx(float(death.vanguard_runtime.death_metal_icd),90.0),"Selected Mosh should immediately trigger baseline Lightning Breath with its own 90-second Death Metal ICD.");TestSupport.check(errors,not VanguardSystem.try_death_metal(death,true) and is_equal_approx(VanguardSystem.death_metal_floor(death,9999.0),float(death.hp)-1.0),"Death Metal should not recurse and should preserve a one-Health lethal floor.")
	return errors
