extends RefCounted

const TestSupport=preload("res://tests/test_support.gd")

static func run(main:Node)->Array:
	var errors:Array=[];var monk_save_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Monk")
	if monk_save_index<0:TestSupport.check(errors,false,"The testing save should include a Monk fixture.");return errors
	var cleric_save_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Cleric");var beastmaster_save_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Beastmaster");var guardian_save_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Guardian")
	main.state.selected_team=[monk_save_index,cleric_save_index,beastmaster_save_index,guardian_save_index];main.state.active_team=main.state.selected_team.duplicate();main.start_monk_testing_zone()
	var hero:Dictionary=main.heroes.filter(func(member):return str(member.get("class",""))=="Monk")[0];main.selected=main.heroes.find(hero);var friend:Dictionary=main.heroes.filter(func(member):return member!=hero and str(member.get("class",""))=="Cleric")[0];var beastmaster:Dictionary=main.heroes.filter(func(member):return str(member.get("class",""))=="Beastmaster")[0];var misha:Dictionary=beastmaster.beastmaster_runtime.misha;var foe:Dictionary=main.enemies[0]
	main.load_monk_test_build(hero,0);hero.pos=Vector2(300,400);friend.pos=hero.pos+Vector2(100,0);foe.pos=hero.pos+Vector2(120,0);hero.critical_chance=0.0;foe.armor=0.0
	TestSupport.check(errors,not main.cast_monk_ability(1,friend.pos) and not main.cast_monk_ability(2,foe.pos) and not main.cast_monk_ability(4,hero.pos),"W/E should reject manual activation and D should be empty before a Guild-12 Ally choice.")
	var disposable:Dictionary=main.BeastmasterSystem.create_beast(beastmaster,"lesser",hero.pos+Vector2(80,0));beastmaster.beastmaster_runtime.lesser_beasts=[disposable]
	TestSupport.check(errors,disposable not in main.monk_dash_candidates(hero) and misha in main.monk_dash_candidates(hero) and hero not in main.monk_dash_candidates(hero),"Live Dash candidates should reject disposable beasts, include Misha, and reject self.")

	main.load_monk_test_build(hero,1);hero.pos=Vector2(300,400);friend.pos=hero.pos+Vector2(100,0);friend.hp=friend.max_hp-1000.0;friend.active_effects=[];main.CombatSystem.apply_control(friend,"stun",8.0);main.CombatSystem.apply_control(friend,"root",8.0);var before:=float(friend.hp)
	TestSupport.check(errors,main.cast_monk_dash(hero,friend) and float(friend.hp)>before and not main.StatusEffectSystem.has_control(friend,"stun") and not main.StatusEffectSystem.has_control(friend,"root") and main.CombatSystem.is_protected(friend),"Allied Dash should cleanse only Stun/Root before ready Breath and apply Sanctified Protected.")
	TestSupport.check(errors,is_equal_approx(float(hero.monk_runtime.breath_cooldown),10.0) and main.active_movement_multiplier(friend)>1.29,"Heavenly Zeal Breath should start its passive cooldown and grant 30% movement speed.")
	main.update_monk_runtime(1.1);TestSupport.check(errors,main.cast_monk_ally(hero,hero.pos+Vector2(80,0)) and main.unit_by_combat_id(str(hero.monk_runtime.ally.combat_id))==hero.monk_runtime.ally and hero.monk_runtime.ally in main.player_combat_summons(),"Spirit Ally should be targetable through the shared combat registry.")
	friend.hp=friend.max_hp*.5;var spirit_before:=float(friend.hp);main.update_monk_runtime(1.0);TestSupport.check(errors,float(friend.hp)>spirit_before,"Spirit Ally should heal nearby eligible allies for 2% maximum Health each second.")
	var ally_anchor:Dictionary=hero.monk_runtime.ally;main.MonkSystem.advance(hero,.25);TestSupport.check(errors,main.cast_monk_dash(hero,ally_anchor),"The Monk should be able to Dash to their own selected Ally.")

	main.load_monk_test_build(hero,2);hero.pos=Vector2(300,400);foe.pos=hero.pos+Vector2(100,0);foe.hp=15000.0;foe.max_hp=15000.0;foe.armor=0.0;foe.active_effects=[];main.CombatSystem.apply_control(foe,"stun",8.0);var enemy_before:=float(foe.hp)
	TestSupport.check(errors,main.cast_monk_dash(hero,foe) and main.MonkSystem.reach_active(hero) and float(foe.hp)<enemy_before and int(hero.monk_runtime.third_counter)==1 and int(hero.monk_runtime.telemetry.hundred_strikes)==6,"Enemy Dash should activate Reach before its attack, execute six qualifying Hundred Fists attacks, and retain modulo-three Trait state.")
	TestSupport.check(errors,float(hero.monk_runtime.telemetry.controlled_damage)>0.0 and is_equal_approx(float(hero.monk_runtime.reach_remaining),4.0),"Controlled Assault and Blazing Fists should be active during the Dash attack sequence.")
	main.update_monk_runtime(.1);TestSupport.check(errors,main.cast_monk_ally(hero,hero.pos+Vector2(50,0)),"Earth Ally should place in its selected build.");main.update_monk_runtime(.1);TestSupport.check(errors,not friend.get("temporary_armor_sources",[]).filter(func(source):return str(source.get("id","")).begins_with("monk_earth:")).is_empty(),"Earth Ally should grant level-scaled Universal Armor through the shared Armor pipeline.")

	main.load_monk_test_build(hero,3);hero.pos=friend.pos;TestSupport.check(errors,main.cast_monk_ally(hero,hero.pos+Vector2(30,0)),"Air Ally should place in its selected build.");main.update_monk_runtime(.1);TestSupport.check(errors,is_equal_approx(main.AbilityPowerSystem.apply(100.0,friend),110.0),"Air Ally should grant exactly 10% Ability Power through the shared pipeline.")
	friend.hp=friend.max_hp*.2;hero.monk_runtime.breath_cooldown=0.0;var echo_before:=float(friend.hp);main.monk_breath(hero,friend);var primary_gain:=float(friend.hp)-echo_before;main.update_monk_runtime(3.01);TestSupport.check(errors,primary_gain>0.0 and float(friend.hp)-echo_before>primary_gain,"Echo of Heaven should repeat its snapshotted recipient healing after three seconds without recursively applying primary extras.")

	main.load_monk_test_build(hero,1);hero.pos=friend.pos;friend.hp=500.0;friend.armor=0.0;friend.shield=0.0;friend.active_effects=[];TestSupport.check(errors,main.MonkSystem.start_palm(hero,friend),"Divine Palm should cast on an eligible allied Hero.");var lethal:Dictionary=main.deal_damage(foe,friend,1000.0,"basic_ability","true","Palm lethal",false,"",[],false);TestSupport.check(errors,not bool(lethal.defeated) and float(friend.hp)>0.0 and hero.monk_runtime.palm.is_empty(),"Palm should intercept lethal damage before defeat hooks and restore Health.")
	main.load_monk_test_build(hero,2);hero.pos=Vector2(300,400);for enemy in main.enemies:enemy.pos=hero.pos+Vector2(70,0);enemy.hp=15000.0;enemy.max_hp=15000.0;enemy.armor=0.0
	TestSupport.check(errors,main.MonkSystem.start_seven(hero),"Seven-Sided Strike should start from its Heroic slot.");main.update_monk_runtime(.1);TestSupport.check(errors,main.CombatSystem.is_invulnerable(hero),"Seven-Sided Strike should make Monk Invulnerable while active.");main.update_monk_runtime(2.0);TestSupport.check(errors,int(hero.monk_runtime.telemetry.seven_strikes)==11 and hero.monk_runtime.seven.is_empty(),"Transgression should resolve exactly eleven highest-current-Health strikes over the live runtime.")
	return errors
