extends RefCounted
const TestSupport=preload("res://tests/test_support.gd")

static func configure(main:Node,hero:Dictionary,build_index:int)->void:
	var build:Dictionary=main.CrusaderData.TEST_BUILDS[build_index];var level:=int(build.level);hero.level=level;hero.base_power=main.CrusaderData.scaled(float(main.CrusaderData.VALUES.basic_attack_damage),level);hero.power=hero.base_power;hero.damage=hero.base_power;hero.max_hp=main.CrusaderData.scaled(float(main.CrusaderData.VALUES.health),level);hero.hp=hero.max_hp;hero.selected_heroic_id=str(build.heroic);hero.selected_talents=build.talents.duplicate(true);hero.ability_cds=[0.0,0.0,0.0,0.0,0.0];hero.shield=0.0;hero.shield_sources=[];hero.active_effects=[];main.CrusaderSystem.initialize_runtime(hero,true)

static func run(main:Node)->Array:
	var errors:Array=[];var crusader_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Crusader")
	if crusader_index<0:TestSupport.check(errors,false,"The testing save should include a Crusader fixture.");return errors
	var cleric_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Cleric");var guardian_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Guardian");var paladin_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Paladin")
	main.state.selected_team=[crusader_index,cleric_index,guardian_index,paladin_index];main.state.active_team=main.state.selected_team.duplicate();main.start_crusader_testing_zone()
	var hero:Dictionary=main.heroes.filter(func(member):return str(member.get("class",""))=="Crusader")[0];main.selected=main.heroes.find(hero);var ally:Dictionary=main.heroes.filter(func(member):return str(member.get("class",""))=="Cleric")[0];var foe:Dictionary=main.enemies[0];hero.pos=Vector2(330,390);hero.facing_direction=Vector2.RIGHT;ally.pos=hero.pos+Vector2(40,0);foe.pos=hero.pos+Vector2(70,0);foe.hp=15000.0;foe.max_hp=15000.0;foe.armor=0.0
	configure(main,hero,0);var before:=float(foe.hp);TestSupport.check(errors,main.cast_crusader_ability(0,foe.pos) and float(foe.hp)<before and main.StatusEffectSystem.has_control(foe,"slow"),"Live Punish should damage and Slow a frontal target.")
	hero.ability_cds[1]=0.0;foe.pos=hero.pos+Vector2(130,0);var old_pos:=Vector2(foe.pos);TestSupport.check(errors,main.cast_crusader_ability(1,foe.pos),"Live Condemn should begin its preparation.");main.update_crusader_runtime(1.0);TestSupport.check(errors,Vector2(foe.pos).distance_to(hero.pos)<old_pos.distance_to(hero.pos) and main.StatusEffectSystem.has_control(foe,"stun"),"Condemn should pull a controllable target and apply its short Stun after one second.")
	var boss:Dictionary=main.enemies.filter(func(enemy):return str(enemy.get("target_category",""))=="boss")[0];boss.pos=hero.pos+Vector2(140,0);boss.hp=15000.0;boss.max_hp=15000.0;hero.ability_cds[1]=0.0;main.cast_crusader_ability(1,boss.pos);var boss_pos:=Vector2(boss.pos);main.update_crusader_runtime(1.0);TestSupport.check(errors,Vector2(boss.pos)==boss_pos,"Boss displacement immunity should reject Condemn's pull without weakening its damage path.")
	configure(main,hero,2);var pack:Array=main.enemies.filter(func(enemy):return not bool(enemy.get("control_profile",{}).get("blind_immune",false))).slice(0,3);for index in pack.size():pack[index].pos=hero.pos+Vector2(100+index*8,(index-1)*12);pack[index].hp=15000.0;pack[index].max_hp=15000.0;pack[index].armor=0.0
	TestSupport.check(errors,main.cast_crusader_ability(2,hero.pos+Vector2.RIGHT*200.0) and int(hero.crusader_runtime.e_slot.current_charges)==1,"Zealous Glare should spend only one of two live E charges.");TestSupport.check(errors,int(hero.crusader_runtime.authority.size())>=3,"A three-target live Shield Glare should arm Blinding Authority for the same damage packet.")
	configure(main,hero,1);hero.hp=hero.max_hp-1000.0;TestSupport.check(errors,main.cast_crusader_ability(4,hero.pos) and main.StatusEffectSystem.is_unstoppable(hero) and float(hero.shield)>0.0,"Iron Skin should create its named Shield and source-owned Unstoppable.");main.deal_damage(foe,hero,float(hero.shield)+1.0,"basic_action","physical","Break",false,"",[],false);main.sync_crusader_runtime_states();TestSupport.check(errors,not main.StatusEffectSystem.is_unstoppable(hero),"Breaking Iron Skin early should immediately end its owned Unstoppable.")
	configure(main,hero,0);hero.pos=Vector2(330,390);TestSupport.check(errors,main.cast_crusader_ability(3,hero.pos+Vector2(250,0)) and not hero.crusader_runtime.falling.is_empty(),"Falling Sword should enter its steerable airborne state.");main.update_crusader_runtime(2.0);TestSupport.check(errors,hero.crusader_runtime.falling.is_empty(),"Falling Sword should land deterministically after two seconds.")
	configure(main,hero,2);for index in range(5):main.enemies[index].pos=hero.pos+Vector2(90+index*25,0);main.enemies[index].hp=15000.0;main.enemies[index].max_hp=15000.0
	TestSupport.check(errors,main.cast_crusader_ability(3,hero.pos+Vector2.RIGHT*200.0) and float(hero.ability_cds[3])==65.0,"Blessed Shield should use its current 65-second cooldown.");TestSupport.check(errors,float(hero.crusader_runtime.telemetry.blessed_stuns)>=3.0,"Radiating Faith should propagate live shield Stuns through the pack.")
	configure(main,hero,1);ally.hp=ally.max_hp-1000.0;var ally_before:=float(ally.hp);for index in range(3):main.enemies[index].pos=hero.pos+Vector2(50+index*20,0);main.enemies[index].hp=15000.0;main.enemies[index].max_hp=15000.0
	TestSupport.check(errors,main.cast_crusader_ability(3,hero.pos+Vector2(100,0)),"Heaven's Fury build should enter Falling Sword.");main.update_crusader_runtime(.25);TestSupport.check(errors,int(hero.crusader_runtime.falling.barrages)==1 and float(hero.ability_cds[3])<=47.0 and float(ally.hp)>ally_before,"One Heaven's Fury barrage should hit up to three enemies, heal nearby allies, and reduce R per enemy impact.")
	configure(main,hero,2);ally.shield=0.0;ally.shield_sources=[];ally.pos=hero.pos+Vector2(40,0);hero.ability_cds[1]=0.0;TestSupport.check(errors,main.cast_crusader_ability(1,hero.pos),"Blinded by the Light should arm from a ready Condemn.");main.update_crusader_runtime(1.0);TestSupport.check(errors,float(ally.shield)>=float(ally.max_hp)*.25 and is_equal_approx(float(hero.crusader_runtime.light_icd),60.0),"A ready Condemn should grant the recipient-scaled three-second party Shield and start its 60-second ICD.")
	configure(main,hero,3);hero.shield=0.0;hero.shield_sources=[];hero.hp=hero.max_hp;main.deal_damage(foe,hero,float(hero.max_hp)+100.0,"basic_action","physical","Lethal",false,"",[],false);TestSupport.check(errors,float(hero.hp)>0.0 and float(hero.shield)>0.0 and is_equal_approx(float(hero.crusader_runtime.indestructible_icd),120.0),"Live fatal damage should be intercepted by Indestructible's full-Health Shield and 120-second ICD.")
	configure(main,hero,1);hero.shield=0.0;hero.shield_sources=[];main.cast_crusader_ability(4,hero.pos);main.deal_damage(foe,hero,float(hero.shield)*.5,"basic_action","physical","Chip",false,"",[],false);main.sync_crusader_runtime_states();var damaged_shield:=float(hero.shield);for index in range(5):main.enemies[index].pos=hero.pos+Vector2(55+index*4,(index-2)*8);main.enemies[index].hp=15000.0;main.enemies[index].max_hp=15000.0;hero.ability_cds[0]=0.0;hero.facing_direction=Vector2.RIGHT
	main.cast_crusader_ability(0,hero.pos+Vector2.RIGHT*100.0);TestSupport.check(errors,float(hero.shield)>damaged_shield and float(hero.shield)<=float(hero.crusader_runtime.iron_skin.maximum),"A live five-contact Q should restore modified Iron Skin without overshielding.")
	TestSupport.check(errors,main.combat_blockers.size()>0 and main.enemies.size()>=6,"Crusader Testing Range should include blockers and multi-target fixtures.")
	return errors
