extends RefCounted

const MonkData=preload("res://scripts/data/monk_data.gd")
const MonkSystem=preload("res://scripts/systems/monk_system.gd")
const StatusEffectSystem=preload("res://scripts/systems/status_effect_system.gd")
const TestSupport=preload("res://tests/test_support.gd")

static func hero(talents:Dictionary={},heroic:String="",level:int=1)->Dictionary:
	var unit:={"class":"Monk","combat_id":"hero:monk","combat_affiliation":"player","combat_team":"player","level":level,"pos":Vector2.ZERO,"hp":MonkData.scaled(float(MonkData.VALUES.health),level),"max_hp":MonkData.scaled(float(MonkData.VALUES.health),level),"selected_talents":talents,"selected_heroic_id":heroic,"ability_cds":[0.0,0.0,0.0,0.0,0.0],"active_effects":[]}
	MonkSystem.initialize_runtime(unit,true,"test:monk");return unit
static func ally(id:String="ally",summon:bool=false,major:bool=false)->Dictionary:return {"combat_id":id,"combat_affiliation":"player","combat_team":"player","hp":1000.0,"max_hp":1000.0,"pos":Vector2(50,0),"summoned_unit":summon,"permanent_companion":major,"ordinary_heal_eligible":major,"active_effects":[]}
static func enemy(id:String="enemy")->Dictionary:return {"combat_id":id,"combat_affiliation":"enemy","combat_team":"enemy","hp":1000.0,"max_hp":1000.0,"pos":Vector2(50,0),"target_category":"standard","active_effects":[]}
static func hit(raw:float=100.0,resolved:float=100.0)->Dictionary:return {"raw_amount":raw,"resolved_damage":resolved,"health_damage":resolved,"evaded":false,"immune":false}

static func run()->Array:
	var errors:Array=[];var base:=hero();var definition:Dictionary=MonkData.CLASS_DEFINITION
	TestSupport.check(errors,str(definition.primary_role)=="Support" and not bool(definition.uses_mana) and is_equal_approx(float(definition.threat_modifier),1.0),"Monk should be a resource-free Support with 1.0 Threat.")
	TestSupport.check(errors,is_equal_approx(float(definition.base_health),2080.0) and is_equal_approx(float(definition.base_power),64.0) and is_equal_approx(float(definition.basic_action_interval),.5),"Monk chassis values should match the audited source build.")
	TestSupport.check(errors,int(MonkSystem.q_state(base).charges)==2 and is_equal_approx(float(base.monk_runtime.q_slot.recharge_duration),12.0),"Radiant Dash should begin with two sequential 12-second charges.")
	var friend:=ally();var foe:=enemy();var disposable:=ally("disposable",true,false);var misha:=ally("misha",true,true)
	TestSupport.check(errors,not MonkSystem.valid_ally_anchor(base,base) and MonkSystem.valid_ally_anchor(base,friend) and MonkSystem.valid_ally_anchor(base,misha) and not MonkSystem.valid_ally_anchor(base,disposable) and MonkSystem.valid_enemy_anchor(base,foe),"Dash anchors should allow other Heroes, major companions, and enemies while rejecting self and disposable summons.")
	TestSupport.check(errors,bool(MonkSystem.spend_dash(base,friend).allied) and int(MonkSystem.q_state(base).charges)==1 and not bool(MonkSystem.spend_dash(base,foe).get("cast",false)),"Dash should spend a charge and enforce its 0.25-second intercast gate.")
	MonkSystem.advance(base,.25);TestSupport.check(errors,bool(MonkSystem.spend_dash(base,foe).enemy) and int(MonkSystem.q_state(base).charges)==0,"Dash should accept an enemy after the intercast gate and leave zero charges.")
	MonkSystem.advance(base,12.0);TestSupport.check(errors,int(MonkSystem.q_state(base).charges)==1,"Sequential Dash recharge should restore one charge after 12 seconds.")
	var blind:=hero({"tier_4":"monk_l18_1"});TestSupport.check(errors,int(MonkSystem.q_state(blind).max_charges)==3 and is_equal_approx(float(blind.monk_runtime.q_slot.recharge_duration),10.0),"Blinding Speed should grant three charges and a ten-second recharge.")
	var epiphany:=hero({"tier_8":"monk_l30_3"});MonkSystem.spend_dash(epiphany,friend);MonkSystem.advance(epiphany,.25);var epi:=MonkSystem.spend_dash(epiphany,foe);TestSupport.check(errors,bool(epi.epiphany) and int(MonkSystem.q_state(epiphany).charges)==2 and is_equal_approx(float(epiphany.monk_runtime.epiphany_icd),70.0),"Epiphany should refill the current maximum only when a spend reaches zero.")
	var reach:=hero({"tier_4":"monk_l18_3","tier_5":"monk_l21_3"});StatusEffectSystem.apply_control(foe,"stun",2.0);TestSupport.check(errors,MonkSystem.activate_reach(reach) and is_equal_approx(float(reach.monk_runtime.reach_remaining),4.0) and is_equal_approx(MonkSystem.controlled_multiplier(reach,foe),1.25),"Blazing Fists and Controlled Assault should combine during Reach on a controlled enemy.")
	var trans:=hero({"tier_1":"monk_l9_1"});MonkSystem.note_basic_attack(trans,hit());MonkSystem.note_basic_attack(trans,hit());var trans_proc:=MonkSystem.note_basic_attack(trans,hit());TestSupport.check(errors,bool(trans_proc.triggered) and is_equal_approx(float(trans_proc.healing),104.0) and is_equal_approx(float(trans.monk_runtime.trait_speed_remaining),2.5),"Transcendence should heal and grant speed on exactly the third successful attack.")
	var iron:=hero({"tier_1":"monk_l9_2"});MonkSystem.note_basic_attack(iron,hit());MonkSystem.note_basic_attack(iron,hit());var iron_proc:=MonkSystem.note_basic_attack(iron,hit(100.0,50.0));TestSupport.check(errors,is_equal_approx(float(iron_proc.bonus_damage),110.0),"Iron Fists should derive +110% from the attack's raw amount so Armor is not applied twice.")
	var insight:=hero({"tier_1":"monk_l9_3"});insight.monk_runtime.insight_progress=99;insight.monk_runtime.third_counter=2;insight.monk_runtime.breath_cooldown=10.0;var completion:=MonkSystem.note_basic_attack(insight,hit());TestSupport.check(errors,bool(insight.monk_runtime.insight_complete) and is_equal_approx(float(completion.cdr),0.0) and is_equal_approx(float(insight.monk_runtime.breath_cooldown),10.0),"The quest-completing Insight hit should not retroactively gain cooldown reduction.")
	insight.monk_runtime.third_counter=2;var completed:=MonkSystem.note_basic_attack(insight,hit());TestSupport.check(errors,is_equal_approx(float(completed.cdr),1.75) and is_equal_approx(float(insight.monk_runtime.breath_cooldown),8.25),"Later completed-Insight third hits should reduce Q/W/E by 1.75 seconds.")
	var fists:=hero({"tier_1":"monk_l9_2","tier_8":"monk_l30_1"});fists.monk_runtime.third_counter=2;fists.monk_runtime.breath_cooldown=10.0;var fists_proc:=MonkSystem.note_basic_attack(fists,hit());TestSupport.check(errors,is_equal_approx(float(fists_proc.healing),52.0) and is_equal_approx(float(fists_proc.bonus_damage),110.0) and is_equal_approx(float(fists_proc.cdr),.875),"Fists of Legend should retain the selected Trait and add half of both unchosen effects, including immediate completed Insight CDR.")
	for record in [{"talent":"monk_l12_1","kind":"spirit","hp":150.0},{"talent":"monk_l12_2","kind":"earth","hp":400.0},{"talent":"monk_l12_3","kind":"air","hp":300.0}]:
		var owner:=hero({"tier_2":record.talent});var placed:=MonkSystem.cast_ally(owner,Vector2(10,0));TestSupport.check(errors,bool(placed.cast) and str(placed.ally.ally_kind)==record.kind and is_equal_approx(float(placed.ally.max_hp),record.hp) and is_equal_approx(float(owner.monk_runtime.ally_cooldown),45.0),"%s Ally should use its exact Health, ten-second duration, and 45-second cooldown."%str(record.kind).capitalize())
	var palm:=hero({"tier_7":"monk_l27_r1"},"monk_l15_r1");TestSupport.check(errors,MonkSystem.start_palm(palm,palm) and is_equal_approx(MonkSystem.consume_palm_for(palm,str(palm.combat_id)),2100.0),"Peaceful Repose Palm should allow self and heal 175% of 1200 on lethal trigger.")
	var failed:=hero({"tier_7":"monk_l27_r1"},"monk_l15_r1");MonkSystem.start_palm(failed,friend);MonkSystem.advance(failed,4.0);TestSupport.check(errors,failed.monk_runtime.palm.is_empty() and is_equal_approx(float(failed.ability_cds[3]),5.0),"An untriggered Peaceful Repose Palm should leave five seconds of cooldown.")
	var seven:=hero({"tier_7":"monk_l27_r2"},"monk_l15_r2");TestSupport.check(errors,MonkSystem.start_seven(seven) and int(seven.monk_runtime.seven.strikes_left)==11 and is_equal_approx(float(seven.monk_runtime.seven.remaining),2.0),"Transgression should create eleven Seven-Sided strikes over two seconds.")
	return errors
