extends RefCounted
const TestSupport=preload("res://tests/test_support.gd")

static func configure(main:Node,hero:Dictionary,build_index:int)->void:
	var build:Dictionary=main.PaladinData.TEST_BUILDS[build_index];var level:=int(build.level);hero.level=level;hero.base_power=main.PaladinData.scaled(float(main.PaladinData.VALUES.basic_attack_damage),level);hero.power=hero.base_power;hero.damage=hero.base_power;hero.max_hp=main.PaladinData.scaled(float(main.PaladinData.VALUES.health),level);hero.hp=hero.max_hp;hero.selected_heroic_id=str(build.heroic);hero.selected_talents=build.talents.duplicate(true);hero.ability_cds=[0.0,0.0,0.0,0.0,0.0];main.PaladinSystem.initialize_runtime(hero,true)

static func run(main:Node)->Array:
	var errors:Array=[];var paladin_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Paladin")
	if paladin_index<0:TestSupport.check(errors,false,"The testing save should include a Paladin fixture.");return errors
	var cleric_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Cleric");var beastmaster_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Beastmaster");var guardian_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Guardian")
	main.state.selected_team=[paladin_index,cleric_index,beastmaster_index,guardian_index];main.state.active_team=main.state.selected_team.duplicate();main.start_paladin_testing_zone()
	var hero:Dictionary=main.heroes.filter(func(member):return str(member.get("class",""))=="Paladin")[0];main.selected=main.heroes.find(hero);var friend:Dictionary=main.heroes.filter(func(member):return str(member.get("class",""))=="Cleric")[0];var foe:Dictionary=main.enemies[0];hero.pos=Vector2(330,390);friend.pos=hero.pos+Vector2(60,0);foe.pos=hero.pos+Vector2(70,0);foe.hp=15000.0;foe.max_hp=15000.0;foe.armor=0.0
	configure(main,hero,0);hero.hp=hero.max_hp-1000.0;var hp_before:=float(hero.hp);var enemy_before:=float(foe.hp);TestSupport.check(errors,main.cast_paladin_ability(0,hero.pos),"Q should begin charging through live runtime.");main.PaladinSystem.advance(hero,1.5);TestSupport.check(errors,bool(hero.paladin_runtime.charge.active) and main.cast_paladin_ability(0,hero.pos) and float(hero.hp)>hp_before and float(foe.hp)<enemy_before,"Maximum Q should remain armed, then explicitly release to heal and damage.")
	hero.ability_cds[1]=0.0;foe.pos=hero.pos+Vector2(60,0);hero.facing_direction=Vector2.RIGHT;TestSupport.check(errors,main.cast_paladin_ability(1,foe.pos),"W should begin charging.");main.PaladinSystem.advance(hero,1.5);TestSupport.check(errors,main.cast_paladin_ability(1,foe.pos) and main.StatusEffectSystem.has_control(foe,"stun"),"Maximum W should hit its frontal arc, displace, and Stun.")
	configure(main,hero,2);hero.pos=Vector2(330,390);foe.pos=hero.pos+Vector2(180,0);TestSupport.check(errors,main.cast_paladin_ability(3,hero.pos) and not hero.paladin_runtime.sacred.is_empty(),"Sacred Ground should activate in the Paladin Range.");main.update_paladin_runtime(.1);var blocker_count:int=main.combat_blockers.filter(func(blocker):return str(blocker.get("shape",""))=="ring").size();TestSupport.check(errors,blocker_count==1 and not bool(main.combat_blockers[-1].blocks_projectiles),"Sacred Ground should publish one non-projectile ring blocker.")
	hero.ability_cds[2]=0.0;TestSupport.check(errors,main.cast_paladin_ability(2,hero.pos+Vector2(220,0)),"E should begin inside Sacred Ground.");main.PaladinSystem.advance(hero,1.5);var old_center:=Vector2(hero.paladin_runtime.sacred.center);TestSupport.check(errors,main.cast_paladin_ability(2,hero.pos+Vector2(220,0)) and Vector2(hero.paladin_runtime.sacred.center)!=old_center and is_equal_approx(float(hero.paladin_runtime.sacred.remaining),7.0),"Hallowed Ground should relocate the active wall to E landing and reset seven seconds.")
	configure(main,hero,3);hero.ability_cds[4]=0.0;TestSupport.check(errors,main.cast_paladin_ability(4,hero.pos) and bool(hero.paladin_runtime.divine_purpose_primed),"D should prime Divine Purpose without auto-casting.");TestSupport.check(errors,main.cast_paladin_ability(2,hero.pos+Vector2(200,0)) and bool(hero.paladin_runtime.charge.maximum_charge),"The next E should arm immediately at full charge.");TestSupport.check(errors,main.cast_paladin_ability(2,hero.pos+Vector2(200,0)) and not bool(hero.paladin_runtime.divine_purpose_primed) and main.StatusEffectSystem.is_unstoppable(hero),"Committing the empowered E should consume D and grant Seraphim Unstoppable.")
	configure(main,hero,0);hero.ability_cds[4]=9.0;main.begin_ability(2,"pc");TestSupport.check(errors,bool(hero.paladin_runtime.charge.active) and main.ability_aiming,"PC button-down should start a charged cast and its aiming state.");main.PaladinSystem.advance(hero,.75);TestSupport.check(errors,main.confirm_aim_at(hero.pos+Vector2(120,0)) and not bool(hero.paladin_runtime.charge.active),"PC confirm should commit the current partial charge and updated aim.")
	return errors
