extends RefCounted

const TestSupport=preload("res://tests/test_support.gd")

static func run(main:Node)->Array:
	var errors:Array=[]
	var save_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Death Knight")
	if save_index<0:TestSupport.check(errors,false,"The testing save should include a Death Knight runtime fixture.");return errors
	main.state.selected_team=[save_index];main.state.active_team=[save_index];main.start_death_knight_testing_zone();var hero:Dictionary=main.heroes.filter(func(member):return str(member.get("class",""))=="Death Knight")[0];main.selected=main.heroes.find(hero)
	TestSupport.check(errors,main.testing_zone_mode=="death_knight_range" and main.enemies.any(func(enemy):return str(enemy.get("target_category",""))=="summon") and main.enemies.filter(func(enemy):return str(enemy.get("target_category",""))=="boss").size()==2,"Death Knight Range should launch with summon, ordinary Boss, and Root-immune Boss fixtures.")

	main.load_death_knight_test_build(hero,0);hero.critical_chance=0.0;hero.pos=Vector2(300,400);hero.dest=hero.pos
	for foe in main.enemies:foe.pos=Vector2(1100,650);foe.hp=10000.0;foe.max_hp=10000.0;foe.armor=0.0;foe.active_effects=[]
	var elite:Dictionary=main.enemies.filter(func(enemy):return str(enemy.get("target_category",""))=="elite")[0];elite.pos=hero.pos+Vector2(50,0);main.focused_enemy_index=main.enemies.find(elite);var before:=float(elite.hp)
	TestSupport.check(errors,main.cast_death_knight_frostmourne(hero) and is_equal_approx(before-float(elite.hp),166.0) and int(hero.death_knight_runtime.frostmourne_stacks)==1 and is_equal_approx(float(hero.death_knight_runtime.frostmourne_cooldown),12.0),"Live Frostmourne should immediately deliver separate 95 and 71 packets, progress on an Elite hit, and begin cooldown on attack.")
	hero.ability_cds[0]=0.0;before=float(elite.hp);TestSupport.check(errors,main.cast_death_knight_death_coil(hero,elite,false) and is_equal_approx(before-float(elite.hp),164.0) and is_equal_approx(float(hero.ability_cds[0]),9.0),"Live enemy Death Coil should deal 164 and begin its nine-second cooldown.")
	hero.ability_cds[0]=0.0;hero.hp=hero.max_hp-500.0;var hero_before:=float(hero.hp);TestSupport.check(errors,main.cast_death_knight_death_coil(hero,null,true) and is_equal_approx(float(hero.hp)-hero_before,275.0),"Live manually targeted self Death Coil should heal the Death Knight for 275.")
	hero.ability_cds[1]=0.0;elite.pos=hero.pos+Vector2(200,0);before=float(elite.hp);TestSupport.check(errors,main.cast_death_knight_howling_blast(hero,elite.pos) and is_equal_approx(before-float(elite.hp),68.0) and main.StatusEffectSystem.has_control(elite,"root"),"Live Howling Blast should deal 68 in its final area and Root for 1.25 seconds.")

	main.load_death_knight_test_build(hero,0);elite.pos=hero.pos+Vector2(80,0);elite.active_effects=[];before=float(elite.hp);TestSupport.check(errors,main.cast_death_knight_tempest(hero) and not main.DeathKnightSystem.action_allowed(hero,0),"Frozen Tempest should toggle on and lock the other action slots in a non-Eternal build.");main.update_death_knight_runtime(1.0);TestSupport.check(errors,float(elite.hp)<before and main.StatusEffectSystem.has_control(elite,"slow"),"A live Frozen Tempest tick should damage and apply source-aware suppression after one second.");TestSupport.check(errors,main.cast_death_knight_tempest(hero) and is_equal_approx(float(hero.death_knight_runtime.tempest.cooldown),8.0),"Baseline Frozen Tempest should start an eight-second cooldown on manual exit.")
	main.load_death_knight_test_build(hero,1);elite.active_effects=[];main.cast_death_knight_tempest(hero);main.update_death_knight_runtime(1.0);TestSupport.check(errors,main.DeathKnightSystem.action_allowed(hero,0) and is_equal_approx(float(hero.death_knight_runtime.suppression[str(elite.combat_id)].stacks),.2),"Eternal Winter should keep other actions available and double the live suppression ramp.");TestSupport.check(errors,main.cast_death_knight_tempest(hero) and is_equal_approx(float(hero.death_knight_runtime.tempest.cooldown),7.0),"Borean Winds should start a seven-second Tempest cooldown on manual exit.")

	main.load_death_knight_test_build(hero,2);var ghouls:Array=main.DeathKnightSystem.cast_army(hero);TestSupport.check(errors,ghouls.size()==12 and int(hero.death_knight_runtime.army_slot.current_charges)==0,"The live Frostmourne weapon build should consume six Army charges into twelve Legion Ghouls.")
	main.update_death_knight_runtime(1.0);TestSupport.check(errors,float(hero.death_knight_runtime.telemetry.ghoul_attacks)>0.0,"Live Army Ghouls should acquire nearby eligible enemies and attack independently.")
	var hostile:Dictionary=main.enemies[0];hostile.pos=Vector2(ghouls[0].pos);TestSupport.check(errors,main.enemy_target_entity(hostile,main.heroes.find(hero)) in ghouls and main.unit_by_combat_id(str(ghouls[0].combat_id))==ghouls[0],"Enemy targeting and combat-ID lookup should expose an owner's nearer Ghoul as a real targetable summon entity.")

	main.load_death_knight_test_build(hero,3);elite.pos=hero.pos+Vector2(250,0);elite.active_effects=[];hero.ability_cds[3]=0.0;before=float(elite.hp);TestSupport.check(errors,main.cast_death_knight_heroic(hero,elite.pos) and float(elite.hp)<before and main.StatusEffectSystem.has_control(elite,"root") and main.CombatSystem.is_blinded(elite),"Live Absolute Zero should hit, Root, and Blind an ordinary target before scheduling its Slow.");main.update_death_knight_runtime(2.6);TestSupport.check(errors,main.StatusEffectSystem.has_control(elite,"slow"),"Absolute Zero should apply its Slow after the Root completes.")

	main.load_death_knight_test_build(hero,4);elite.pos=hero.pos+Vector2(100,0);elite.active_effects=[];main.CombatSystem.apply_control(elite,"slow",2.0,.2);hero.ability_cds[0]=0.0;TestSupport.check(errors,main.cast_death_knight_death_coil(hero,elite,false) and is_equal_approx(main.OutgoingDamageReductionSystem.multiplier(elite),.6),"Death's Dominion should use the target's pre-cast control state for live 40% outgoing damage reduction.")
	main.load_death_knight_test_build(hero,2);hero.selected_talents["tier_1"]="death_knight_l9_3";main.DeathKnightSystem.initialize_runtime(hero,true,{},"test:rime_live");elite.active_effects=[];hero.hp=hero.max_hp;var rime_packet:Dictionary=main.deal_controlled_damage(elite,hero,500.0,"basic_ability","physical","stun",1.0);TestSupport.check(errors,is_equal_approx(float(rime_packet.damage.resolved_damage),125.0) and bool(rime_packet.control.applied) and is_equal_approx(main.IncomingDamageReductionSystem.multiplier(hero),.25),"A live damage-and-control packet should activate Rime before damage so the triggering 500 becomes 125.")
	hero.active_effects=[];hero.control_profile={"stun_multiplier":0.0};hero.hp=hero.max_hp;rime_packet=main.deal_controlled_damage(elite,hero,500.0,"basic_ability","physical","stun",1.0);TestSupport.check(errors,is_equal_approx(float(rime_packet.damage.resolved_damage),500.0) and not bool(rime_packet.control.applied) and is_equal_approx(main.IncomingDamageReductionSystem.multiplier(hero),1.0),"A resisted control should neither activate Rime nor reduce its accompanying damage.")
	return errors
