extends RefCounted
const CrusaderData=preload("res://scripts/data/crusader_data.gd")
const CrusaderSystem=preload("res://scripts/systems/crusader_system.gd")
const CombatSystem=preload("res://scripts/systems/combat_system.gd")
const StatusEffectSystem=preload("res://scripts/systems/status_effect_system.gd")
const TestSupport=preload("res://tests/test_support.gd")

static func hero(talents:Dictionary={},heroic:String="crusader_l15_r1",level:int=1)->Dictionary:
	var unit:={"class":"Crusader","combat_id":"hero:crusader","combat_affiliation":"player","combat_team":"player","level":level,"pos":Vector2.ZERO,"hp":CrusaderData.scaled(float(CrusaderData.VALUES.health),level),"max_hp":CrusaderData.scaled(float(CrusaderData.VALUES.health),level),"selected_talents":talents,"selected_heroic_id":heroic,"ability_cds":[0.0,0.0,0.0,0.0,0.0],"active_effects":[]}
	CrusaderSystem.initialize_runtime(unit,true);return unit

static func run()->Array:
	var errors:Array=[];var definition:=CrusaderData.CLASS_DEFINITION
	TestSupport.check(errors,str(definition.primary_role)=="Tank" and not bool(definition.uses_mana) and is_equal_approx(float(definition.threat_modifier),1.5),"Crusader should be a resource-free Tank with 1.5 Threat.")
	TestSupport.check(errors,is_equal_approx(float(definition.base_health),2625.0) and is_equal_approx(float(definition.base_power),99.0) and is_equal_approx(float(definition.basic_action_interval),1.1),"Crusader chassis should match source build 2.55.17.97771.")
	TestSupport.check(errors,CrusaderData.TALENT_TIERS.size()==8 and CrusaderData.TALENT_TIERS.reduce(func(total,tier):return total+tier.option_ids.size(),0)==22,"Crusader should expose all eight mapped tiers and twenty-two retained/reworked choices.")
	var baseline:=hero();var q:=CrusaderSystem.q_plan(baseline,1);TestSupport.check(errors,is_equal_approx(float(q.damage),113.0) and is_equal_approx(float(q.slow),.5) and bool(q.decays),"Baseline Punish should use 113 damage and its decaying 50% Slow.")
	TestSupport.check(errors,CrusaderSystem.begin_condemn(baseline) and is_equal_approx(float(baseline.ability_cds[1]),10.0),"Condemn should begin a one-second preparation on a ten-second cooldown.");CrusaderSystem.advance(baseline,1.0);TestSupport.check(errors,CrusaderSystem.take_condemn_resolution(baseline),"Condemn should resolve exactly after its preparation delay.")
	var zealous:=hero({"tier_1":"crusader_l9_1"});TestSupport.check(errors,int(zealous.crusader_runtime.e_slot.max_charges)==2 and CrusaderSystem.spend_glare(zealous),"Zealous Glare should grant two Shield Glare charges.");CrusaderSystem.advance(zealous,.5);var e:=CrusaderSystem.e_plan(zealous,3,0);TestSupport.check(errors,is_equal_approx(float(e.damage),100.3) and int(zealous.crusader_runtime.e_slot.current_charges)==1,"Zealous Glare should add 70% damage without consuming both charges.")
	var fortress:=hero({"tier_1":"crusader_l9_2"})
	for attack in 5:CrusaderSystem.note_basic_attack(fortress,"enemy",true)
	TestSupport.check(errors,int(fortress.crusader_runtime.fortress_stacks)==4 and is_equal_approx(float(CrusaderSystem.note_basic_attack(fortress,"enemy",true).fortress_armor),100.0),"Divine Fortress should cap at four 25 Level-1 Armor stacks.");CrusaderSystem.advance(fortress,4.0);TestSupport.check(errors,int(fortress.crusader_runtime.fortress_stacks)==0,"Divine Fortress stacks should expire together after four seconds.")
	var laws:=hero({"tier_1":"crusader_l9_3"});var skin:=CrusaderSystem.iron_skin_plan(laws);TestSupport.check(errors,is_equal_approx(float(laws.crusader_runtime.laws.per_tick)*5.0,float(laws.max_hp)*.20) and is_equal_approx(float(skin.duration),4.0),"Laws of Hope should fold a 20% maximum-Health heal over five seconds into Iron Skin.")
	var subdue:=hero({"tier_2":"crusader_l12_1"});var empowered:=CrusaderSystem.q_plan(subdue,2);TestSupport.check(errors,is_equal_approx(float(empowered.slow),.70) and not bool(empowered.decays),"Subdue should apply its non-decaying 70% Slow after two contacts.");CrusaderSystem.q_plan(subdue,4);TestSupport.check(errors,bool(subdue.crusader_runtime.subdue_complete) and not bool(CrusaderSystem.q_plan(subdue,1).decays),"A four-target Punish should permanently complete Subdue for the encounter.")
	var eternal:=hero({"tier_2":"crusader_l12_2"});eternal.ability_cds[1]=8.0;CrusaderSystem.mark_condemn(eternal,["a","b","c"]);TestSupport.check(errors,eternal.crusader_runtime.eternal_marks.size()==3,"Eternal Retaliation should independently mark every Condemn contact.");var retaliation:=CrusaderSystem.note_basic_attack(eternal,"b",true);TestSupport.check(errors,is_equal_approx(float(retaliation.w_cdr),1.0) and is_equal_approx(float(eternal.ability_cds[1]),7.0) and not eternal.crusader_runtime.eternal_marks.has("b"),"A primary Basic Attack should consume only its target's mark for one second of W cooldown reduction.")
	var hold:=hero({"tier_2":"crusader_l12_3"});var held:=CrusaderSystem.iron_skin_plan(hold);TestSupport.check(errors,is_equal_approx(float(held.maximum),1134.0) and is_equal_approx(float(hold.ability_cds[4]),20.0),"Hold Your Ground should add 40% Shield and remove two seconds from Iron Skin cooldown.")
	var sins:=hero({"tier_4":"crusader_l18_1"});CrusaderSystem.mark_sins(sins,"target");CrusaderSystem.advance(sins,2.0);CrusaderSystem.note_basic_attack(sins,"target",true);TestSupport.check(errors,is_equal_approx(float(sins.crusader_runtime.sins.target),3.0),"A primary Basic Attack should refresh the owner-scoped Sins Exposed duration.")
	var conviction:=hero({"tier_4":"crusader_l18_2"});TestSupport.check(errors,is_equal_approx(CrusaderSystem.movement_multiplier(conviction),1.1),"Conviction should grant 10% passive Movement Speed.");CrusaderSystem.begin_condemn(conviction);TestSupport.check(errors,is_equal_approx(CrusaderSystem.movement_multiplier(conviction),1.2),"Conviction should replace the passive bonus with 20% while Condemn prepares.")
	var steed:=hero({"tier_4":"crusader_l18_3"});var long_skin:=CrusaderSystem.iron_skin_plan(steed);TestSupport.check(errors,is_equal_approx(float(long_skin.duration),6.0),"Steed Charge should fold two seconds into Iron Skin with no mount action.");CrusaderSystem.spend_glare(steed);TestSupport.check(errors,is_equal_approx(float(steed.crusader_runtime.iron_skin.remaining),8.0),"Shield Glare should extend an existing Steed Charge Iron Skin by two seconds.")
	var roar:=hero({"tier_5":"crusader_l21_1"});TestSupport.check(errors,is_equal_approx(float(CrusaderSystem.q_plan(roar,1).damage),169.5) and is_equal_approx(float(CrusaderSystem.q_plan(roar,2).damage),282.5),"Roar's multi-target bonus should replace, not add to, its single-target bonus.")
	var fury:=hero({"tier_5":"crusader_l21_2"});CrusaderSystem.w_plan(fury,7);TestSupport.check(errors,int(fury.crusader_runtime.holy_fury_stacks)==5 and is_equal_approx(float(fury.crusader_runtime.holy_fury_remaining),5.0),"Holy Fury should use the shared five-contact cap for five seconds.")
	var authority:=hero({"tier_5":"crusader_l21_3"});CrusaderSystem.set_authority(authority,["a","b"]);TestSupport.check(errors,is_equal_approx(CrusaderSystem.authority_multiplier(authority,"a"),1.0),"Blinding Authority should not activate below three Blinds.");CrusaderSystem.set_authority(authority,["a","b","c"]);TestSupport.check(errors,is_equal_approx(CrusaderSystem.authority_multiplier(authority,"a"),4.0) and is_equal_approx(CrusaderSystem.authority_multiplier(authority,"other"),1.0),"Blinding Authority should be owner/target scoped and multiply final Threat by four immediately.")
	var shrinking:=hero({"tier_6":"crusader_l24_1"});TestSupport.check(errors,is_equal_approx(float(CrusaderSystem.w_plan(shrinking,9).reduction),.25),"Shrinking Vacuum should cap at 25% reduction from five contacts.")
	var renewal:=hero({"tier_6":"crusader_l24_2"});CrusaderSystem.mark_condemn(renewal,["a","b"]);CrusaderSystem.spend_glare(renewal);CrusaderSystem.advance(renewal,.5);var renewed:=CrusaderSystem.e_plan(renewal,3,2);TestSupport.check(errors,is_equal_approx(float(renewed.cdr),4.0) and is_equal_approx(float(renewal.crusader_runtime.e_slot.timers[0]),8.5),"Holy Renewal should reduce E recharge by 1.5 seconds per Condemned contact and one second otherwise.")
	var momentum:=hero({"tier_6":"crusader_l24_3"});momentum.ability_cds[4]=12.0;CrusaderSystem.q_plan(momentum,7);TestSupport.check(errors,is_equal_approx(float(momentum.ability_cds[4]),7.0),"Blessed Momentum should reduce Iron Skin cooldown once per Q contact up to five.")
	var falling:=hero({},"crusader_l15_r1");TestSupport.check(errors,CrusaderSystem.begin_falling(falling) and is_equal_approx(float(falling.ability_cds[3]),50.0) and is_equal_approx(float(falling.crusader_runtime.falling.remaining),2.0),"Falling Sword should start a two-second airborne window on a fifty-second cooldown.")
	var radiating:=hero({"tier_7":"crusader_l27_r2"},"crusader_l15_r2");TestSupport.check(errors,str(radiating.selected_heroic_id)=="crusader_l15_r2" and int(CrusaderData.VALUES.radiating_targets)==5 and is_equal_approx(float(CrusaderData.VALUES.radiating_stun),1.75),"Radiating Faith should define five targets and a uniform 1.75-second Stun.")
	var indestructible:=hero({"tier_8":"crusader_l30_1"});TestSupport.check(errors,CrusaderSystem.try_indestructible(indestructible,true) and not CrusaderSystem.try_indestructible(indestructible,true) and is_equal_approx(float(indestructible.crusader_runtime.indestructible_icd),120.0),"Indestructible should intercept one fatal hit per 120 seconds without recursive retrigger.")
	var light:=hero({"tier_8":"crusader_l30_2"});light.crusader_runtime.light_icd=60.0;CrusaderSystem.spend_glare(light);CrusaderSystem.advance(light,.5);CrusaderSystem.e_plan(light,5,0);TestSupport.check(errors,is_equal_approx(float(light.crusader_runtime.light_icd),19.5),"Five Shield Glare contacts should remove forty seconds from Blinded by the Light's ticking ICD.")
	var unbreakable:=hero({"tier_8":"crusader_l30_3"});CrusaderSystem.iron_skin_plan(unbreakable);unbreakable.crusader_runtime.iron_skin.current=100.0;var restored:=CrusaderSystem.restore_iron_skin(unbreakable,9);TestSupport.check(errors,is_equal_approx(restored,202.5),"Unbreakable Crusade should restore 25% of modified Iron Skin per qualifying Basic Ability cast at five contacts.")
	var long_loop:=hero({"tier_1":"crusader_l9_1","tier_2":"crusader_l12_3","tier_4":"crusader_l18_3","tier_8":"crusader_l30_3"});var loop_skin:=CrusaderSystem.iron_skin_plan(long_loop);CrusaderSystem.spend_glare(long_loop);CrusaderSystem.advance(long_loop,.5);CrusaderSystem.spend_glare(long_loop);TestSupport.check(errors,is_equal_approx(float(long_loop.crusader_runtime.iron_skin.remaining),9.5),"Zealous Glare's two casts should each extend Steed Charge once, including a zero-contact cast, while elapsed time still ticks.");long_loop.crusader_runtime.iron_skin.current=100.0;var large_restore:=CrusaderSystem.restore_iron_skin(long_loop,5);TestSupport.check(errors,is_equal_approx(float(loop_skin.maximum),1134.0) and is_equal_approx(large_restore,283.5),"Hold Your Ground should increase Unbreakable Crusade's five-contact restoration basis.");long_loop.crusader_runtime.iron_skin.active=false;TestSupport.check(errors,is_equal_approx(CrusaderSystem.restore_iron_skin(long_loop,5),0.0),"Unbreakable Crusade should not resurrect a broken Iron Skin.")
	var controlled:={"active_effects":[]};StatusEffectSystem.apply_source_unstoppable(controlled,"iron",4.0);TestSupport.check(errors,StatusEffectSystem.is_unstoppable(controlled) and not bool(CombatSystem.apply_control(controlled,"stun",1.0).applied),"Source-owned Unstoppable should reject control while its Shield source exists.");StatusEffectSystem.remove_source_unstoppable(controlled,"iron");TestSupport.check(errors,not StatusEffectSystem.is_unstoppable(controlled),"Removing the Iron Skin source should end only its owned Unstoppable.")
	return errors
