extends RefCounted

const TestSupport=preload("res://tests/test_support.gd")

static func configure(main:Node,hero:Dictionary,build_index:int)->void:main.load_spiritweaver_test_build(hero,build_index)

static func run(main:Node)->Array:
	var errors:Array=[]
	var spirit_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Spirit Weaver")
	if spirit_index<0:TestSupport.check(errors,false,"The testing save should include a Spirit Weaver fixture.");return errors
	var cleric_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Cleric");var guardian_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Guardian");var vanguard_index:int=main.state.heroes.find_custom(func(saved):return str(saved.get("class",""))=="Vanguard")
	main.state.selected_team=[spirit_index,cleric_index,guardian_index,vanguard_index];main.state.active_team=main.state.selected_team.duplicate();main.start_spiritweaver_testing_zone()
	var hero:Dictionary=main.heroes.filter(func(member):return str(member.get("class",""))=="Spirit Weaver")[0];main.selected=main.heroes.find(hero);var ally:Dictionary=main.heroes.filter(func(member):return str(member.get("class",""))=="Cleric")[0];var tank:Dictionary=main.heroes.filter(func(member):return str(member.get("class",""))=="Guardian")[0];var foe:Dictionary=main.enemies[0]
	hero.pos=Vector2(325,420);ally.pos=hero.pos+Vector2(45,0);tank.pos=hero.pos+Vector2(85,0);ally.hp=ally.max_hp*.20;tank.hp=tank.max_hp*.35;foe.pos=hero.pos+Vector2(90,0);foe.hp=20000.0;foe.max_hp=20000.0;foe.armor=0.0
	configure(main,hero,0);hero.pos=Vector2(325,420);ally.pos=hero.pos+Vector2(45,0);tank.pos=hero.pos+Vector2(85,0);ally.hp=ally.max_hp*.20;tank.hp=tank.max_hp*.35
	var ally_before:=float(ally.hp);var tank_before:=float(tank.hp);main.resolve_spiritweaver_basic_heal(hero,ally,{"effective_amount":60.0,"overhealing":0.0});TestSupport.check(errors,float(tank.hp)>tank_before and is_equal_approx(float(tank.hp)-tank_before,float(hero.basic_heal_amount)*.5),"Live Spirit Weaver Basic Heal should bounce once at 50% to the lowest-percentage second Hero.")
	TestSupport.check(errors,main.cast_spiritweaver_ability(0,ally.pos) and hero.spiritweaver_runtime.latest_q.healed.size()==3 and float(ally.hp)>ally_before,"Live Chain Heal should heal three distinct Hero recipients with explicit cast state.")
	configure(main,hero,2);hero.pos=Vector2(325,420);tank.pos=hero.pos+Vector2(60,0);foe.pos=tank.pos+Vector2(30,0);tank.hp=tank.max_hp*.40;var tank_max:=float(tank.max_hp);TestSupport.check(errors,main.cast_spiritweaver_ability(1,tank.pos),"Live Lightning Shield should accept an allied Hero bearer.");main.update_spiritweaver_runtime(.5);TestSupport.check(errors,float(foe.hp)<20000.0 and float(tank.max_hp)>tank_max and float(tank.shield)>0.0,"Lightning Shield should damage live enemies while Stormcaller and Earth Shield affect its Hero bearer.")
	configure(main,hero,1);hero.pos=Vector2(325,420);var blocker_center:Vector2=main.combat_blockers[0].rect.get_center();TestSupport.check(errors,main.spiritweaver_valid_ground(blocker_center)==Vector2.INF,"Earthbind placement should reject blocked ground instead of accepting the requested point unchanged.");var placement:=Vector2(560,320);TestSupport.check(errors,main.cast_spiritweaver_ability(2,placement) and not hero.spiritweaver_runtime.totem.is_empty(),"Live E should create one targetable, source-owned Earthbind deployable.");var totem:Dictionary=hero.spiritweaver_runtime.totem;var original_hp:=float(totem.hp);var original_remaining:=float(totem.remaining);TestSupport.check(errors,main.cast_spiritweaver_ability(2,placement+Vector2(60,0)) and is_equal_approx(float(totem.hp),original_hp) and is_equal_approx(float(totem.remaining),original_remaining),"Colossal reposition should preserve the existing Totem's Health and duration.");var w_on_totem:bool=main.cast_spiritweaver_ability(1,totem.pos);var last_w:Dictionary=hero.spiritweaver_runtime.lightning_shields[-1] if not hero.spiritweaver_runtime.lightning_shields.is_empty() else {};TestSupport.check(errors,w_on_totem and bool(last_w.get("bearer_is_totem",false)),"Grounded Totem should make the active Totem a legal W bearer (cast=%s, talent=%s, distance=%.2f, bearer=%s)."%[str(w_on_totem),str(main.SpiritWeaverSystem.has_talent(hero,"spiritweaver_l18_1")),Vector2(hero.pos).distance_to(Vector2(totem.pos)),str(last_w.get("bearer_id","none"))])
	configure(main,hero,3);hero.pos=Vector2(325,420);ally.pos=hero.pos+Vector2(45,0);main.StatusEffectSystem.apply_source_control(ally,"test_control","stun",3.0,0.0);ally.hp=ally.max_hp*.30;var purge_before:=float(ally.hp);TestSupport.check(errors,main.cast_spiritweaver_ability(4,ally.pos) and not main.StatusEffectSystem.has_control(ally,"stun") and float(ally.hp)>purge_before,"Ally Purge should cleanse, apply Unstoppable, and trigger Purification only after a successful removal.")
	configure(main,hero,3);hero.pos=Vector2(325,420);main.StatusEffectSystem.apply_source_control(hero,"test_self","stun",3.0,0.0);hero.hp=hero.max_hp*.50;TestSupport.check(errors,main.cast_spiritweaver_ability(4,hero.pos) and not main.StatusEffectSystem.has_control(hero,"stun"),"Cleansing Tempest should permit self-Purge through the Stun action lock.")
	configure(main,hero,3);hero.pos=Vector2(325,420);foe.pos=hero.pos+Vector2(80,0);foe.active_effects=[{"id":"test_positive","beneficial":true,"dispellable":true,"remaining_duration":4.0}];main.begin_trait("mobile");var mobile_aim_ready:bool=main.ability_aiming and main.aimed_ability_slot==4 and main.aimed_from_touch;var mobile_confirmed:bool=main.confirm_aim_at(foe.pos);TestSupport.check(errors,mobile_aim_ready and mobile_confirmed and not foe.active_effects.any(func(effect):return str(effect.get("id",""))=="test_positive") and main.CombatSystem.control_amount(foe,"slow")>0.0,"PC/mobile dual-target Purge aiming should confirm enemies, dispel explicit positive effects, and apply its decaying Slow.")
	configure(main,hero,3);hero.pos=Vector2(325,420);ally.pos=hero.pos+Vector2(45,0);main.StatusEffectSystem.apply_source_control(hero,"test_lock","stun",3.0,0.0);TestSupport.check(errors,not main.cast_spiritweaver_ability(0,ally.pos),"Stun should keep Q/W/E/R action-locked even with Cleansing Tempest selected.");hero.active_effects=[];main.StatusEffectSystem.apply_source_control(hero,"test_root","root",3.0,0.0);TestSupport.check(errors,main.cast_spiritweaver_ability(0,ally.pos),"Root should stop movement without incorrectly preventing an in-range Spirit Weaver cast.")
	configure(main,hero,2);hero.pos=Vector2(325,420);for member in main.heroes:member.pos=hero.pos+Vector2(main.heroes.find(member)*35,0);member.hp=member.max_hp*.60
	TestSupport.check(errors,main.cast_spiritweaver_ability(3,hero.pos),"Live Bloodlust should cast from the selected Heroic slot.");var bloodlust_effects:Array=main.heroes.filter(func(member):return member.active_effects.any(func(effect):return str(effect.get("effect_family",""))=="bloodlust"));TestSupport.check(errors,bloodlust_effects.size()==4,"Bloodlust should affect eligible nearby Heroes but not disposable summons or Totems.")
	configure(main,hero,0);hero.pos=Vector2(325,420);ally.pos=hero.pos+Vector2(45,0);ally.hp=ally.max_hp*.10;TestSupport.check(errors,main.cast_spiritweaver_ability(3,ally.pos) and not hero.spiritweaver_runtime.pending_ancestral.is_empty(),"Ancestral Healing should schedule its delayed heal on another allied Hero.");var ancestral_before:=float(ally.hp);main.update_spiritweaver_runtime(1.0);TestSupport.check(errors,float(ally.hp)>ancestral_before,"Ancestral Healing should resolve after its audited one-second delay.")
	configure(main,hero,2);hero.pos=Vector2(325,420);foe.pos=hero.pos+Vector2(100,0);foe.armor=50.0;main.update_spiritweaver_runtime(3.0);TestSupport.check(errors,bool(hero.spiritweaver_runtime.wolf_active),"The live automatic trait should enter Ghost Wolf after three seconds without a personal action.");var foe_before:=float(foe.hp);main.resolve_spiritweaver_basic_attack(hero,foe,{"raw_amount":100.0,"resolved_damage":50.0});var expected_lunge:float=60.0*(1.0-main.CombatSystem.calculate_armor_reduction(50.0,int(hero.level)));TestSupport.check(errors,is_equal_approx(foe_before-float(foe.hp),expected_lunge) and not bool(hero.spiritweaver_runtime.wolf_active),"Ghost Wolf's 60% bonus strike should derive from the Basic Attack's raw amount and apply Armor exactly once.")
	TestSupport.check(errors,main.combat_blockers.size()>=1 and main.enemies.size()>=9 and main.heroes.size()==4,"Spirit Weaver Testing Range should include party, category, Boss-control, training, and blocker fixtures.")
	return errors
