extends RefCounted

const TestSupport = preload("res://tests/test_support.gd")
const SaveManager = preload("res://scripts/systems/save_manager.gd")
const ProfessionData = preload("res://scripts/data/profession_data.gd")
const ProfessionSystem = preload("res://scripts/systems/profession_system.gd")
const InventorySystem = preload("res://scripts/systems/inventory_system.gd")
const ItemData = preload("res://scripts/data/item_data.gd")

static func add_item(state:Dictionary,definition_id:String,instance_id:String,rarity:String="Common")->Dictionary:
	var item:=ItemData.create_instance(definition_id,instance_id);item.rarity=rarity;item.trait_capacity=ProfessionSystem.trait_capacity(rarity);InventorySystem.add_equipment(state,item);InventorySystem.transfer_entry(state,instance_id,"depot");return item

static func run()->Array:
	var errors:Array=[];var state:=SaveManager.testing_state();state.gold=9999
	var brann:=str(state.heroes[0].hero_id);var sera:=str(state.heroes[1].hero_id);var wren:=str(state.heroes[2].hero_id);var nyx:=str(state.heroes[3].hero_id)
	var learned:=ProfessionSystem.learn_profession(state,brann,"forgecraft");TestSupport.check(errors,bool(learned.success) and not bool(ProfessionSystem.learn_profession(state,brann,"alchemy").success),"A member should learn exactly one profession.")
	ProfessionSystem.discover_recipe(state,"forge_ashwood_bulwark",true);ProfessionSystem.grant_xp(state,brann,20);TestSupport.check(errors,int(ProfessionSystem.progress(state,brann).profession_rank)==1,"Profession Rank should advance when XP, introduction milestone, and Hero Prestige requirements are met.")
	var low_prestige:=SaveManager.fresh_state();low_prestige.gold=100;var low_id:=str(low_prestige.heroes[0].hero_id);ProfessionSystem.learn_profession(low_prestige,low_id,"alchemy");ProfessionSystem.grant_xp(low_prestige,low_id,100);ProfessionSystem.add_milestone(low_prestige,low_id,"first_order");TestSupport.check(errors,int(ProfessionSystem.progress(low_prestige,low_id).profession_rank)==1,"Profession Rank II should remain locked without the required Hero Prestige Rank I.")
	TestSupport.check(errors,ProfessionSystem.trait_capacity("Common")==1 and ProfessionSystem.trait_capacity("Uncommon")==2 and ProfessionSystem.trait_capacity("Rare")==3 and ProfessionSystem.trait_capacity("Epic")==4 and ProfessionSystem.trait_capacity("Legendary")==4,"Common through Legendary trait capacities should follow the prototype rule.")
	var parents:Array=[]
	for index in 3:
		var parent:=add_item(state,"ashwood_bulwark","parent_%d"%index);parent.item_xp=index*7;parent.traits=["warden"] if index==0 else [];parents.append(parent.duplicate(true))
	var order:=ProfessionSystem.start_profession_order(state,brann,"forge_ashwood_bulwark",{"item_instance_ids":["parent_0","parent_1","parent_2"],"preferred_trait":"warden"});TestSupport.check(errors,bool(order.success),"Basic Forgecraft should start without an Alchemy product.")
	var completed:=ProfessionSystem.complete_profession_order(state,str(order.order_id));var combined:Dictionary={}
	for item in state.item_instances:
		if item.get("contained_parent_items",[]).size()==3:combined=item;break
	TestSupport.check(errors,bool(completed.success) and not combined.is_empty() and str(combined.rarity)=="Common" and str(combined.definition_id)=="ashwood_bulwark","Known basic synthesis should guarantee its form and retain same rarity.")
	TestSupport.check(errors,combined.get("traits",[]).size()<=1,"Synthesis should enforce rarity trait capacity.")
	InventorySystem.transfer_entry(state,str(combined.instance_id),"depot");var separation:=ProfessionSystem.separate_item(state,brann,str(combined.instance_id));TestSupport.check(errors,bool(separation.success) and separation.restored.size()==3 and int(separation.restored[2].item_xp)==14,"Separation should delete a Depot result and restore the exact parent instances and development to the Vault.")
	TestSupport.check(errors,true,"Separation intentionally has no ingredient-refund output.")
	ProfessionSystem.progress(state,brann).profession_rank=2;ProfessionSystem.discover_recipe(state,"forge_marchwarden_evolution",true);InventorySystem.add_material(state,"basic_catalyst",1)
	for index in 3:add_item(state,"pilgrims_vestment","evolution_parent_%d"%index,"Uncommon")
	var evolution:=ProfessionSystem.start_profession_order(state,brann,"forge_marchwarden_evolution",{"item_instance_ids":["evolution_parent_0","evolution_parent_1","evolution_parent_2"]});if bool(evolution.success):ProfessionSystem.complete_profession_order(state,str(evolution.order_id));var evolved:Dictionary=state.item_instances.filter(func(item):return str(item.get("definition_id",""))=="marchwarden_plate" and not item.get("contained_parent_items",[]).is_empty()).front() if state.item_instances.any(func(item):return str(item.get("definition_id",""))=="marchwarden_plate" and not item.get("contained_parent_items",[]).is_empty()) else {};TestSupport.check(errors,bool(evolution.success) and str(evolved.get("rarity",""))=="Rare","A valid known evolution recipe should deliberately advance Uncommon parents to a chosen Rare form.");var controlled:=ProfessionSystem.evaluate_synthesis_result(state,"forge_ashwood_bulwark",parents);TestSupport.check(errors,bool(controlled.success) and controlled.controlled_pool==["ashwood_bulwark"],"Discovery evaluation should remain inside a controlled compatible result pool.")
	ProfessionSystem.learn_profession(state,sera,"enchanting");ProfessionSystem.grant_xp(state,sera,20);ProfessionSystem.choose_specialization(state,sera,1,"enchant_guided_inheritance")
	var prepared:=ProfessionSystem.prepare_parent_set(state,sera,["parent_0","parent_1","parent_2"],"warden",false);TestSupport.check(errors,bool(prepared.success),"Guided Inheritance should prepare an existing compatible trait.")
	TestSupport.check(errors,not bool(ProfessionSystem.refine_inherited_trait(state,sera,"parent_1","unrelated_major_trait").success),"Enchanting should not create unrelated traits from nothing.")
	var protected:=add_item(state,"pilgrims_vestment","protected_item");protected.favourite=true;TestSupport.check(errors,not bool(ProfessionSystem.disenchant_item(state,sera,"protected_item").success),"Favourite items should be blocked from disenchanting.")
	protected.favourite=false;protected.rarity="Rare";protected.region="ashwood";protected.traits=["spellward"];var reclaimed:Dictionary=ProfessionSystem.disenchant_item(state,sera,"protected_item");var valid_outputs:bool=bool(reclaimed.success) and reclaimed.outputs.all(func(output):return str(output.material_id) in ProfessionSystem.CLEAN_DISENCHANT_OUTPUTS);TestSupport.check(errors,valid_outputs and ItemData.item_by_instance_id(state.item_instances,"protected_item").is_empty(),"Disenchanting should permanently remove the item and emit only the clean four-family output set.")
	ProfessionSystem.learn_profession(state,wren,"alchemy");ProfessionSystem.discover_recipe(state,"alchemy_basic_catalyst",true);var catalyst:=ProfessionSystem.start_profession_order(state,wren,"alchemy_basic_catalyst");TestSupport.check(errors,bool(catalyst.success),"Alchemy should consume existing world materials for a meaningful processed output.");if bool(catalyst.success):ProfessionSystem.complete_profession_order(state,str(catalyst.order_id));TestSupport.check(errors,state.material_stacks.any(func(stack):return str(stack.material_id)=="basic_catalyst"),"Alchemy should create a Catalyst in the shared Guild Vault.")
	ProfessionSystem.learn_profession(state,nyx,"inscription");ProfessionSystem.discover_rune_pattern(state,"pattern_frostfall");var rune_order:=ProfessionSystem.start_profession_order(state,nyx,"inscription_frostfall");if bool(rune_order.success):ProfessionSystem.complete_profession_order(state,str(rune_order.order_id));var rune_applied:=ProfessionSystem.apply_rune(state,nyx,"mage:q","rune_frostfall");var presentation:=ProfessionSystem.ability_presentation(state,nyx,"mage:q","Flamestrike");TestSupport.check(errors,bool(rune_order.success) and bool(rune_applied.success) and str(presentation.display_name)=="Frostfall" and str(presentation.mechanics_ability_id)=="mage:q","A reusable Rune should alter presentation while retaining the mechanics ability ID.")
	for repeat in 3:
		InventorySystem.add_material(state,"ore",3);InventorySystem.add_material(state,"herbs",1);var mastery_order:=ProfessionSystem.start_profession_order(state,wren,"alchemy_basic_catalyst");if bool(mastery_order.success):ProfessionSystem.complete_profession_order(state,str(mastery_order.order_id))
	TestSupport.check(errors,ProfessionSystem.is_pattern_mastered(state,"alchemy_basic_catalyst") and ProfessionSystem.is_recipe_automation_eligible(state,"alchemy_basic_catalyst") and ProfessionSystem.progress(state,wren).current_profession_order_id=="","Pattern Mastery should only set automation eligibility and should not start production.")
	InventorySystem.add_material(state,"ore",3);InventorySystem.add_material(state,"herbs",1);var persistent_order:=ProfessionSystem.start_profession_order(state,wren,"alchemy_basic_catalyst");var migrated:=SaveManager.migrate_state(state.duplicate(true),true,true);TestSupport.check(errors,bool(persistent_order.success) and migrated.profession_orders.size()==state.profession_orders.size() and str(ProfessionSystem.progress(migrated,wren).current_profession_order_id)==str(persistent_order.order_id),"Profession orders should survive save migration with their member assignment.")
	if bool(persistent_order.success):ProfessionSystem.cancel_profession_order(state,str(persistent_order.order_id))
	var recipes_before:Dictionary=state.guild_recipes.duplicate(true);var unlearned:Dictionary=ProfessionSystem.unlearn_profession(state,brann);TestSupport.check(errors,bool(unlearned.success) and str(ProfessionSystem.progress(state,brann).profession_id)=="" and int(ProfessionSystem.progress(state,brann).profession_xp)==0 and state.guild_recipes==recipes_before,"Unlearning should reset individual progression while preserving guild-wide recipes and mastery.")
	var old_save:=SaveManager.fresh_state();old_save.erase("save_version");old_save.erase("component_versions");old_save.heroes[0].erase("profession_progress");old_save.item_instances=[ItemData.create_instance("pinewatch_bow","legacy_profession_item")];var upgraded:=SaveManager.migrate_state(old_save,true);TestSupport.check(errors,int(upgraded.component_versions.professions)==ProfessionSystem.SAVE_VERSION and upgraded.heroes[0].profession_progress.has("profession_slots") and upgraded.item_instances[0].has("contained_parent_items"),"Old saves should gain versioned profession and item metadata without losing existing state.")
	return errors
